// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'accounting.freezed.dart';

@freezed
sealed class AccountingAsOfRequest with _$AccountingAsOfRequest {
  const AccountingAsOfRequest._();

  const factory AccountingAsOfRequest.current() = AccountingAsOfRequest_Current;
  const factory AccountingAsOfRequest.at({required String asOfUtc}) =
      AccountingAsOfRequest_At;
}

@freezed
sealed class AccountingBridgeError
    with _$AccountingBridgeError
    implements FrbException {
  const AccountingBridgeError._();

  const factory AccountingBridgeError.invalidUtcTimestamp({
    required String field,
    required String value,
  }) = AccountingBridgeError_InvalidUtcTimestamp;
  const factory AccountingBridgeError.invalidLocalDate({
    required String value,
  }) = AccountingBridgeError_InvalidLocalDate;
  const factory AccountingBridgeError.invalidDateRange({
    required String start,
    required String end,
  }) = AccountingBridgeError_InvalidDateRange;
  const factory AccountingBridgeError.invalidRange({
    required String startUtc,
    required String endUtc,
  }) = AccountingBridgeError_InvalidRange;
  const factory AccountingBridgeError.asOfBeforeStart({
    required String asOfUtc,
    required String startUtc,
  }) = AccountingBridgeError_AsOfBeforeStart;
  const factory AccountingBridgeError.futureAsOf({
    required String asOfUtc,
    required String deadlineUtc,
  }) = AccountingBridgeError_FutureAsOf;
  const factory AccountingBridgeError.invalidTimeZone({
    required String timezone,
  }) = AccountingBridgeError_InvalidTimeZone;
  const factory AccountingBridgeError.invalidLocalBoundary({
    required String timezone,
    required String boundary,
  }) = AccountingBridgeError_InvalidLocalBoundary;
  const factory AccountingBridgeError.storage({required String message}) =
      AccountingBridgeError_Storage;
  const factory AccountingBridgeError.staleRevision({
    required String sourceIdentity,
    required PlatformInt64 incoming,
    required PlatformInt64 existing,
  }) = AccountingBridgeError_StaleRevision;
  const factory AccountingBridgeError.producerUnavailable({
    required String message,
  }) = AccountingBridgeError_ProducerUnavailable;
}

class AccountingIntervalDto {
  final String startUtc;
  final String endUtc;
  final AccountingStateDto state;
  final String? appId;
  final String? windowId;
  final String? windowAppId;
  final String? pageId;
  final String? pageWindowId;
  final String sourceIdentity;
  final PlatformInt64 sourceRevision;

  const AccountingIntervalDto({
    required this.startUtc,
    required this.endUtc,
    required this.state,
    this.appId,
    this.windowId,
    this.windowAppId,
    this.pageId,
    this.pageWindowId,
    required this.sourceIdentity,
    required this.sourceRevision,
  });

  @override
  int get hashCode =>
      startUtc.hashCode ^
      endUtc.hashCode ^
      state.hashCode ^
      appId.hashCode ^
      windowId.hashCode ^
      windowAppId.hashCode ^
      pageId.hashCode ^
      pageWindowId.hashCode ^
      sourceIdentity.hashCode ^
      sourceRevision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountingIntervalDto &&
          runtimeType == other.runtimeType &&
          startUtc == other.startUtc &&
          endUtc == other.endUtc &&
          state == other.state &&
          appId == other.appId &&
          windowId == other.windowId &&
          windowAppId == other.windowAppId &&
          pageId == other.pageId &&
          pageWindowId == other.pageWindowId &&
          sourceIdentity == other.sourceIdentity &&
          sourceRevision == other.sourceRevision;
}

@freezed
sealed class AccountingRangeRequest with _$AccountingRangeRequest {
  const AccountingRangeRequest._();

  const factory AccountingRangeRequest.utc({
    required String startUtc,
    required String endUtc,
  }) = AccountingRangeRequest_Utc;
  const factory AccountingRangeRequest.localDate({
    required String localDate,
    required String timezone,
  }) = AccountingRangeRequest_LocalDate;
}

class AccountingSnapshotDto {
  final String requestedStartUtc;
  final String requestedEndUtc;
  final String effectiveStartUtc;
  final String effectiveEndUtc;
  final String observedThroughUtc;
  final AccountingTotalsDto totals;
  final List<AccountingIntervalDto> intervals;
  final List<AttributionTotalDto> apps;
  final List<AttributionTotalDto> windows;
  final List<AttributionTotalDto> pages;
  final SnapshotIntegrityDto integrity;
  final String? timezone;
  final String? localDate;
  final List<LocalHourBucketDto> hours;

  const AccountingSnapshotDto({
    required this.requestedStartUtc,
    required this.requestedEndUtc,
    required this.effectiveStartUtc,
    required this.effectiveEndUtc,
    required this.observedThroughUtc,
    required this.totals,
    required this.intervals,
    required this.apps,
    required this.windows,
    required this.pages,
    required this.integrity,
    this.timezone,
    this.localDate,
    required this.hours,
  });

  @override
  int get hashCode =>
      requestedStartUtc.hashCode ^
      requestedEndUtc.hashCode ^
      effectiveStartUtc.hashCode ^
      effectiveEndUtc.hashCode ^
      observedThroughUtc.hashCode ^
      totals.hashCode ^
      intervals.hashCode ^
      apps.hashCode ^
      windows.hashCode ^
      pages.hashCode ^
      integrity.hashCode ^
      timezone.hashCode ^
      localDate.hashCode ^
      hours.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountingSnapshotDto &&
          runtimeType == other.runtimeType &&
          requestedStartUtc == other.requestedStartUtc &&
          requestedEndUtc == other.requestedEndUtc &&
          effectiveStartUtc == other.effectiveStartUtc &&
          effectiveEndUtc == other.effectiveEndUtc &&
          observedThroughUtc == other.observedThroughUtc &&
          totals == other.totals &&
          intervals == other.intervals &&
          apps == other.apps &&
          windows == other.windows &&
          pages == other.pages &&
          integrity == other.integrity &&
          timezone == other.timezone &&
          localDate == other.localDate &&
          hours == other.hours;
}

enum AccountingStateDto {
  active,
  idle,
  paused,
  privacyExcluded,
  systemGap,
  unknown,
}

class AccountingTotalsDto {
  final PlatformInt64 activeSeconds;
  final PlatformInt64 idleSeconds;
  final PlatformInt64 pausedSeconds;
  final PlatformInt64 privacyExcludedSeconds;
  final PlatformInt64 systemGapSeconds;
  final PlatformInt64 unknownSeconds;
  final PlatformInt64 accountedSeconds;

  const AccountingTotalsDto({
    required this.activeSeconds,
    required this.idleSeconds,
    required this.pausedSeconds,
    required this.privacyExcludedSeconds,
    required this.systemGapSeconds,
    required this.unknownSeconds,
    required this.accountedSeconds,
  });

  @override
  int get hashCode =>
      activeSeconds.hashCode ^
      idleSeconds.hashCode ^
      pausedSeconds.hashCode ^
      privacyExcludedSeconds.hashCode ^
      systemGapSeconds.hashCode ^
      unknownSeconds.hashCode ^
      accountedSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountingTotalsDto &&
          runtimeType == other.runtimeType &&
          activeSeconds == other.activeSeconds &&
          idleSeconds == other.idleSeconds &&
          pausedSeconds == other.pausedSeconds &&
          privacyExcludedSeconds == other.privacyExcludedSeconds &&
          systemGapSeconds == other.systemGapSeconds &&
          unknownSeconds == other.unknownSeconds &&
          accountedSeconds == other.accountedSeconds;
}

class AttributionTotalDto {
  final String id;
  final String? parentId;
  final PlatformInt64 seconds;

  const AttributionTotalDto({
    required this.id,
    this.parentId,
    required this.seconds,
  });

  @override
  int get hashCode => id.hashCode ^ parentId.hashCode ^ seconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttributionTotalDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          parentId == other.parentId &&
          seconds == other.seconds;
}

class LocalHourBucketDto {
  final String stableId;
  final String localDate;
  final int localHour;
  final int utcOffsetSeconds;
  final int fold;
  final String startUtc;
  final String endUtc;
  final AccountingTotalsDto totals;
  final List<AttributionTotalDto> apps;

  const LocalHourBucketDto({
    required this.stableId,
    required this.localDate,
    required this.localHour,
    required this.utcOffsetSeconds,
    required this.fold,
    required this.startUtc,
    required this.endUtc,
    required this.totals,
    required this.apps,
  });

  @override
  int get hashCode =>
      stableId.hashCode ^
      localDate.hashCode ^
      localHour.hashCode ^
      utcOffsetSeconds.hashCode ^
      fold.hashCode ^
      startUtc.hashCode ^
      endUtc.hashCode ^
      totals.hashCode ^
      apps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalHourBucketDto &&
          runtimeType == other.runtimeType &&
          stableId == other.stableId &&
          localDate == other.localDate &&
          localHour == other.localHour &&
          utcOffsetSeconds == other.utcOffsetSeconds &&
          fold == other.fold &&
          startUtc == other.startUtc &&
          endUtc == other.endUtc &&
          totals == other.totals &&
          apps == other.apps;
}

enum SnapshotIntegrityDto { complete, partial }
