// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One closed model choice safe to expose to Flutter.
class AiModelOptionDto {
  /// Stable model identifier accepted by Rust.
  final String id;

  /// Localized product label.
  final String displayName;

  /// `free_local` or `paid_cloud`.
  final String costTier;

  const AiModelOptionDto({
    required this.id,
    required this.displayName,
    required this.costTier,
  });

  @override
  int get hashCode => id.hashCode ^ displayName.hashCode ^ costTier.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiModelOptionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          costTier == other.costTier;
}

/// One closed provider choice safe to expose to Flutter.
class AiProviderOptionDto {
  /// Stable provider identifier accepted by Rust.
  final String id;

  /// Localized product label.
  final String displayName;

  /// Stable privacy/cost description without endpoints.
  final String description;

  /// Whether the provider needs a user-owned API key.
  final bool requiresApiKey;

  /// Whether an explicit aggregate-free connection test is meaningful.
  final bool supportsConnectionTest;

  /// Closed models belonging to this provider.
  final List<AiModelOptionDto> models;

  const AiProviderOptionDto({
    required this.id,
    required this.displayName,
    required this.description,
    required this.requiresApiKey,
    required this.supportsConnectionTest,
    required this.models,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      description.hashCode ^
      requiresApiKey.hashCode ^
      supportsConnectionTest.hashCode ^
      models.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiProviderOptionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          description == other.description &&
          requiresApiKey == other.requiresApiKey &&
          supportsConnectionTest == other.supportsConnectionTest &&
          models == other.models;
}

/// Reply for an explicit, aggregate-free provider connection test.
class AiRecapConnectionReplyDto {
  /// True only after DeepSeek accepts the configured credential.
  final bool success;

  /// Redacted typed failure when the test did not succeed.
  final AiRecapErrorDto? error;

  const AiRecapConnectionReplyDto({required this.success, this.error});

  @override
  int get hashCode => success.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiRecapConnectionReplyDto &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          error == other.error;
}

/// A complete, validated recap result safe to expose to Flutter.
class AiRecapDto {
  /// Closed provider used to generate this report. Missing legacy values are DeepSeek.
  final String providerId;

  /// Logical report type: `daily`, `weekly`, or `monthly`.
  final String scope;

  /// Inclusive local-calendar start date in `YYYY-MM-DD` form.
  final String startDate;

  /// Inclusive local-calendar end date in `YYYY-MM-DD` form.
  final String endDate;

  /// Generation time in UTC RFC3339 form.
  final String generatedAtUtc;

  /// Exact supported model used for generation.
  final String model;

  /// Short Chinese overview with evidence grounded in the sent aggregates.
  final AiRecapStatementDto summary;

  /// One to three validated Chinese observations.
  final List<AiRecapStatementDto> highlights;

  /// One to three validated Chinese suggestions.
  final List<AiRecapStatementDto> suggestions;

  /// Deterministic top application rows computed locally, never by the model.
  final List<AiRecapEvidenceDto> topApplications;

  /// Active seconds across every valid aggregate row, including truncated rows.
  final PlatformInt64 totalActiveSeconds;

  /// Number of valid aggregate applications before the top-12 truncation.
  final PlatformInt64 applicationCount;

  const AiRecapDto({
    required this.providerId,
    required this.scope,
    required this.startDate,
    required this.endDate,
    required this.generatedAtUtc,
    required this.model,
    required this.summary,
    required this.highlights,
    required this.suggestions,
    required this.topApplications,
    required this.totalActiveSeconds,
    required this.applicationCount,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      scope.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      generatedAtUtc.hashCode ^
      model.hashCode ^
      summary.hashCode ^
      highlights.hashCode ^
      suggestions.hashCode ^
      topApplications.hashCode ^
      totalActiveSeconds.hashCode ^
      applicationCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiRecapDto &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          scope == other.scope &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          generatedAtUtc == other.generatedAtUtc &&
          model == other.model &&
          summary == other.summary &&
          highlights == other.highlights &&
          suggestions == other.suggestions &&
          topApplications == other.topApplications &&
          totalActiveSeconds == other.totalActiveSeconds &&
          applicationCount == other.applicationCount;
}

/// Stable, redacted generation error safe to expose to Flutter.
class AiRecapErrorDto {
  /// Stable machine-readable error code defined by the architecture contract.
  final String code;

  /// Whether retrying later without changing the request may succeed.
  final bool retryable;

  const AiRecapErrorDto({required this.code, required this.retryable});

  @override
  int get hashCode => code.hashCode ^ retryable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiRecapErrorDto &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          retryable == other.retryable;
}

/// One aggregate usage row cited by an AI recap statement.
class AiRecapEvidenceDto {
  /// Sanitized application display name sent to the provider.
  final String appName;

  /// Exact active duration sent for this application.
  final PlatformInt64 activeSeconds;

  const AiRecapEvidenceDto({
    required this.appName,
    required this.activeSeconds,
  });

  @override
  int get hashCode => appName.hashCode ^ activeSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiRecapEvidenceDto &&
          runtimeType == other.runtimeType &&
          appName == other.appName &&
          activeSeconds == other.activeSeconds;
}

/// Mutually exclusive result of an explicit recap generation request.
class AiRecapGenerateReplyDto {
  /// Validated recap on success; `None` on failure.
  final AiRecapDto? recap;

  /// Redacted typed failure on failure; `None` on success.
  final AiRecapErrorDto? error;

  const AiRecapGenerateReplyDto({this.recap, this.error});

  @override
  int get hashCode => recap.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiRecapGenerateReplyDto &&
          runtimeType == other.runtimeType &&
          recap == other.recap &&
          error == other.error;
}

/// Mutually exclusive reply for a settings mutation.
class AiRecapSettingsReplyDto {
  /// Refreshed redacted state on success or best-effort state on failure.
  final AiRecapStatusDto status;

  /// Redacted typed failure, if the mutation failed.
  final AiRecapErrorDto? error;

  const AiRecapSettingsReplyDto({required this.status, this.error});

  @override
  int get hashCode => status.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiRecapSettingsReplyDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          error == other.error;
}

/// One validated Chinese statement and its provider-supplied evidence.
class AiRecapStatementDto {
  /// Locally rendered Chinese statement text.
  final String text;

  /// One to three exact references to the sent aggregate rows.
  final List<AiRecapEvidenceDto> evidence;

  const AiRecapStatementDto({required this.text, required this.evidence});

  @override
  int get hashCode => text.hashCode ^ evidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiRecapStatementDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          evidence == other.evidence;
}

/// Provider configuration state safe to expose to Flutter.
class AiRecapStatusDto {
  /// Whether the complete local AI report service is available.
  final bool serviceAvailable;

  /// Whether the current provider/model can generate immediately.
  final bool ready;

  /// Stable selected provider identifier.
  final String selectedProviderId;

  /// Stable selected model identifier.
  final String selectedModelId;

  /// Complete closed provider/model catalog.
  final List<AiProviderOptionDto> providers;

  /// `secure_store`, `legacy_environment`, `none`, or `unavailable`.
  final String credentialSource;

  /// Whether the operating-system secure credential store is available.
  final bool secureStorageAvailable;

  /// Whether a legacy environment key can currently be imported securely.
  final bool environmentMigrationAvailable;

  const AiRecapStatusDto({
    required this.serviceAvailable,
    required this.ready,
    required this.selectedProviderId,
    required this.selectedModelId,
    required this.providers,
    required this.credentialSource,
    required this.secureStorageAvailable,
    required this.environmentMigrationAvailable,
  });

  @override
  int get hashCode =>
      serviceAvailable.hashCode ^
      ready.hashCode ^
      selectedProviderId.hashCode ^
      selectedModelId.hashCode ^
      providers.hashCode ^
      credentialSource.hashCode ^
      secureStorageAvailable.hashCode ^
      environmentMigrationAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiRecapStatusDto &&
          runtimeType == other.runtimeType &&
          serviceAvailable == other.serviceAvailable &&
          ready == other.ready &&
          selectedProviderId == other.selectedProviderId &&
          selectedModelId == other.selectedModelId &&
          providers == other.providers &&
          credentialSource == other.credentialSource &&
          secureStorageAvailable == other.secureStorageAvailable &&
          environmentMigrationAvailable == other.environmentMigrationAvailable;
}
