// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'marketplace.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'plugins/service.dart';

// These functions are ignored because they are not marked as `pub`: `clean_exe_path`, `create_platform_collector`, `csv_field`, `flight_to_dto`, `marketplace_error_token`, `material_to_dto`, `new`, `new`, `parse_date`, `report_data_root`, `run`, `set_paused`, `shutdown_all_in_order`, `shutdown`, `start_ai_report_store`, `with_private_flight`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CollectorRuntime`, `ShutdownOnce`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TimeTraceApi>>
abstract class TimeTraceApi implements RustOpaqueInterface {
  /// Add a new diary entry for a date. Returns the new entry id.
  PlatformInt64 addDiaryEntry({required String date, required String content});

  /// Register a diary image for a date.
  String addDiaryImage({required String date, required String path});

  /// Reads the minimal AI Recap presentation state through a revocable,
  /// first-party entitlement lease. A caller without a verified, enabled AI
  /// Recap entitlement receives the same opaque `plugin_not_projectable`
  /// denial used by other plugin data planes.
  ///
  /// This does not create a provider profile, choose a model, start the AI
  /// composition root, or disclose provider configuration. Those operations
  /// remain unavailable until trusted application bootstrap owns their real
  /// inputs.
  Future<AiRecapStatusDto> aiRecapStatus();

  /// Clear ALL tracked usage data (sessions + page visits).
  void clearData();

  /// Create the API, opening the DB and starting the background monitor.
  static TimeTraceApi create({required String dbPath}) =>
      RustLib.instance.api.crateApiTimeTraceApiCreate(dbPath: dbPath);

  /// Delete a diary entry by id.
  void deleteDiaryEntry({required PlatformInt64 id});

  /// Emit one bounded, structured UI diagnostic without accepting free text.
  ///
  /// Event and error codes must be lowercase canonical tokens. Invalid input
  /// is replaced by a stable rejection event and is never written verbatim.
  void emitUiDiagnostic({
    required String level,
    required String eventCode,
    String? errorCode,
    BigInt? durationMs,
  });

  /// Export usage data for a date range as CSV.
  /// Returns the CSV text (app, date, active_secs, idle_secs).
  String exportCsv({required String start, required String end});

  /// Link a material to a flight session.
  Future<void> flightAddMaterial({
    required PlatformInt64 flightId,
    required PlatformInt64 materialId,
  });

  /// Complete the current active flight.
  Future<PlatformInt64> flightComplete({
    PlatformInt64? satisfaction,
    required String note,
  });

  /// Completes the current flight and optional material as one async,
  /// lifecycle-gated database transaction.
  Future<PlatformInt64> flightCompleteWithMaterial({
    PlatformInt64? satisfaction,
    required String note,
    FlightCompletionMaterialDto? material,
  });

  /// Discard the current active flight.
  Future<PlatformInt64> flightDiscard();

  /// Get the currently active flight session, if any.
  Future<FlightSessionDto?> flightGetCurrent();

  /// Get all materials linked to a flight session, in order.
  Future<List<FlightMaterialDto>> flightGetMaterials({
    required PlatformInt64 flightId,
  });

  /// Get flight sessions within a date range (inclusive).
  Future<List<FlightSessionDto>> flightRange({
    required String start,
    required String end,
  });

  /// Get the most recent N completed flight sessions.
  Future<List<FlightSessionDto>> flightRecent({required PlatformInt64 limit});

  /// Begin a new flight session. Returns the session id.
  /// Returns an error string if an active session already exists.
  Future<PlatformInt64> flightStart();

  /// Hourly active-seconds for one app on a date (24 buckets).
  Int64List getAppHourly({required String appName, required String date});

  /// Extract an exe icon as raw RGBA pixels.
  IconDto? getAppIcon({required String exePath});

  /// Read the current user configuration.
  ConfigDto getConfig();

  /// One-call dashboard payload: usage split + overall stats.
  DashboardDataDto getDashboardData({
    required String start,
    required String end,
  });

  /// Full day detail: active/idle totals, session timeline, diary.
  DayDetailDto getDayDetail({required String date});

  /// Hourly active-seconds for a day (24 buckets) — for the heatmap.
  Int64List getDayHourly({required String date});

  /// The day's draft content, if any.
  String? getDiaryDraft({required String date});

  /// Get all diary entries for a month range (for calendar markers).
  List<(String, String)> getDiaryEntries({
    required String start,
    required String end,
  });

  /// All diary entries in a range with ids + status, newest first.
  List<DiaryEntryDto> getDiaryEntriesDetailed({
    required String start,
    required String end,
  });

  /// Diary image paths in a date range (for calendar cell overlays).
  List<(String, String)> getDiaryImages({
    required String start,
    required String end,
  });

  /// All diary images with their entry link: (date, entry_id, path).
  List<(String, PlatformInt64?, String)> getDiaryImagesDetailed({
    required String start,
    required String end,
  });

  /// Image paths attached to a diary entry (朋友圈 album).
  List<String> getDiaryImagesForEntry({required PlatformInt64 entryId});

  /// Apps active within a specific hour of a date (seconds per app).
  List<AppUsageDto> getHourApps({required String date, required int hour});

  /// All startup entries.
  List<StartupDto> getStartupEntries();

  /// Overall recording statistics.
  StatsDto getStats({required String start, required String end});

  /// Per-app active/idle split for a date range (dates as "YYYY-MM-DD").
  List<AppUsageDto> getUsageSplit({required String start, required String end});

  /// Active seconds for this week (Mon→today) and last week (full).
  (PlatformInt64, PlatformInt64) getWeekTotals();

  /// Page-level breakdown for an app on a date.
  List<PageDto> getWindowTitles({
    required String appName,
    required String date,
  });

  /// Reports whether a database read has entered its non-panicking fallback.
  bool isDatabaseDegraded();

  /// Returns whether TimeTrace is configured to start for the current user.
  bool isSelfStartEnabled();

  /// Whether tracking is currently paused.
  bool isTrackingPaused();

  /// Resolves a Marketplace detail by its typed publisher/plugin identity.
  Future<MarketplacePluginDetailDto> marketplaceDetail({
    required MarketplacePluginRefDto reference,
  });

  /// Installs an exact reviewed Marketplace release with exact consent ids.
  Future<MarketplaceOperationStateDto> marketplaceInstall({
    required MarketplaceInstallRequestDto request,
  });

  /// Lists only host-verified Marketplace presentation DTOs.
  Future<MarketplaceCatalogPageDto> marketplaceList({
    required MarketplaceCatalogQueryDto query,
  });

  /// Get a material by id.
  Future<MaterialDto?> materialGet({required PlatformInt64 id});

  /// Get all materials, newest first.
  Future<List<MaterialDto>> materialList();

  /// Insert or find a material by title. Returns the material id.
  Future<PlatformInt64> materialUpsert({
    required String title,
    required String kind,
    String? sourceUrl,
    String? domain,
    String? localAssetPath,
    required String tags,
    PlatformInt64? rating,
  });

  /// Returns the latest immutable plugin lifecycle and contribution view.
  ///
  /// This uses normal asynchronous FRB dispatch so cloning the bounded DTO
  /// never runs on the Flutter UI isolate.
  Future<HostContributionSnapshotDto> pluginSnapshot();

  /// Publish: promote the day's draft or insert a new published entry.
  PlatformInt64 publishDiary({required String date, required String content});

  /// Remove a diary image.
  void removeDiaryImage({required String path});

  /// Resolve a startup command line to its clean exe path (env-expanded,
  /// quotes/args stripped). Returns None if no .exe is found.
  String? resolveExePath({required String command});

  /// Autosave a draft for a date (one draft per day). Returns its id.
  PlatformInt64 saveDiaryDraft({required String date, required String content});

  /// Persist user configuration (applies on next monitor start).
  void setConfig({required ConfigDto config});

  /// Set the diary entry for a date.
  String setDiary({required String date, required String content});

  /// Link a staged diary image to a diary entry.
  void setDiaryImageEntry({
    required String path,
    required PlatformInt64 entryId,
  });

  /// Enables or disables a plugin on a Rust worker. Marketplace-installed
  /// packages persist their desired state in the Marketplace registry and
  /// reload from that registry; bundled plugins retain their lifecycle path.
  ///
  /// This intentionally uses normal asynchronous FRB dispatch because the
  /// transition atomically persists lifecycle state before publishing.
  Future<HostContributionSnapshotDto> setPluginEnabled({
    required String pluginId,
    required bool enabled,
  });

  /// Configures current-user startup without requiring administrator rights.
  void setSelfStartEnabled({required bool enabled, required bool minimized});

  /// Pause or resume the background tracking monitor.
  void setTrackingPaused({required bool paused});

  /// Stop reports, plugins, and collection in order, then flush diagnostics.
  ///
  /// This method intentionally uses normal asynchronous FRB dispatch because
  /// collector teardown may join platform worker threads. Logging shutdown is
  /// kept inside the same Rust call so the host cannot flush while a collector
  /// is still producing events.
  Future<void> shutdownAll();

  /// Enable/disable a startup entry.
  void toggleStartup({required PlatformInt64 id, required bool enable});

  /// Return the process-start diagnostic level mask for the UI bridge.
  ///
  /// Bit positions follow `trace`, `debug`, `info`, `warn`, and `error`.
  /// The filter is intentionally immutable until the next process start.
  int uiDiagnosticLevelMask();

  /// Update a diary entry's content by id.
  void updateDiaryEntry({required PlatformInt64 id, required String content});
}

/// Safe, entitlement-gated presentation state for the first-party AI Recap
/// renderer. It contains no endpoint, provider profile, credential, report,
/// or usage data.
class AiRecapStatusDto {
  /// Stable host-owned state token. The only currently supported value is
  /// `configuration_required`; the composition root is deliberately not
  /// started until the application has supplied real configuration.
  final String state;

  const AiRecapStatusDto({required this.state});

  @override
  int get hashCode => state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiRecapStatusDto &&
          runtimeType == other.runtimeType &&
          state == other.state;
}

class AppUsageDto {
  final String appName;
  final PlatformInt64 activeSeconds;
  final PlatformInt64 idleSeconds;
  final String exePath;

  const AppUsageDto({
    required this.appName,
    required this.activeSeconds,
    required this.idleSeconds,
    required this.exePath,
  });

  @override
  int get hashCode =>
      appName.hashCode ^
      activeSeconds.hashCode ^
      idleSeconds.hashCode ^
      exePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppUsageDto &&
          runtimeType == other.runtimeType &&
          appName == other.appName &&
          activeSeconds == other.activeSeconds &&
          idleSeconds == other.idleSeconds &&
          exePath == other.exePath;
}

/// User configuration (persisted in AppConfig.json).
class ConfigDto {
  final BigInt pollIntervalMs;
  final BigInt idleThresholdMinutes;
  final bool minimizeToTray;
  final bool startMinimized;
  final bool autoStartTracking;
  final List<String> excludedApps;
  final String dbPath;

  const ConfigDto({
    required this.pollIntervalMs,
    required this.idleThresholdMinutes,
    required this.minimizeToTray,
    required this.startMinimized,
    required this.autoStartTracking,
    required this.excludedApps,
    required this.dbPath,
  });

  @override
  int get hashCode =>
      pollIntervalMs.hashCode ^
      idleThresholdMinutes.hashCode ^
      minimizeToTray.hashCode ^
      startMinimized.hashCode ^
      autoStartTracking.hashCode ^
      excludedApps.hashCode ^
      dbPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigDto &&
          runtimeType == other.runtimeType &&
          pollIntervalMs == other.pollIntervalMs &&
          idleThresholdMinutes == other.idleThresholdMinutes &&
          minimizeToTray == other.minimizeToTray &&
          startMinimized == other.startMinimized &&
          autoStartTracking == other.autoStartTracking &&
          excludedApps == other.excludedApps &&
          dbPath == other.dbPath;
}

/// Combined dashboard payload (one FFI call instead of two).
class DashboardDataDto {
  final List<AppUsageDto> apps;
  final PlatformInt64 activeSeconds;
  final PlatformInt64 idleSeconds;
  final PlatformInt64 totalSeconds;
  final String? since;

  const DashboardDataDto({
    required this.apps,
    required this.activeSeconds,
    required this.idleSeconds,
    required this.totalSeconds,
    this.since,
  });

  @override
  int get hashCode =>
      apps.hashCode ^
      activeSeconds.hashCode ^
      idleSeconds.hashCode ^
      totalSeconds.hashCode ^
      since.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DashboardDataDto &&
          runtimeType == other.runtimeType &&
          apps == other.apps &&
          activeSeconds == other.activeSeconds &&
          idleSeconds == other.idleSeconds &&
          totalSeconds == other.totalSeconds &&
          since == other.since;
}

/// A day's detail: summary + sessions + diary.
class DayDetailDto {
  final String date;
  final PlatformInt64 activeSeconds;
  final PlatformInt64 idleSeconds;
  final PlatformInt64 sessionCount;
  final String diary;
  final List<DaySessionDto> sessions;

  const DayDetailDto({
    required this.date,
    required this.activeSeconds,
    required this.idleSeconds,
    required this.sessionCount,
    required this.diary,
    required this.sessions,
  });

  @override
  int get hashCode =>
      date.hashCode ^
      activeSeconds.hashCode ^
      idleSeconds.hashCode ^
      sessionCount.hashCode ^
      diary.hashCode ^
      sessions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DayDetailDto &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          activeSeconds == other.activeSeconds &&
          idleSeconds == other.idleSeconds &&
          sessionCount == other.sessionCount &&
          diary == other.diary &&
          sessions == other.sessions;
}

/// A single day's session record (for the daily log).
class DaySessionDto {
  final String appName;
  final bool isIdle;
  final PlatformInt64 durationSecs;
  final String startedAt;

  const DaySessionDto({
    required this.appName,
    required this.isIdle,
    required this.durationSecs,
    required this.startedAt,
  });

  @override
  int get hashCode =>
      appName.hashCode ^
      isIdle.hashCode ^
      durationSecs.hashCode ^
      startedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DaySessionDto &&
          runtimeType == other.runtimeType &&
          appName == other.appName &&
          isIdle == other.isIdle &&
          durationSecs == other.durationSecs &&
          startedAt == other.startedAt;
}

/// A diary entry with its publish status ('draft' | 'published').
class DiaryEntryDto {
  final PlatformInt64 id;
  final String date;
  final String content;
  final String status;

  const DiaryEntryDto({
    required this.id,
    required this.date,
    required this.content,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^ date.hashCode ^ content.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiaryEntryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          date == other.date &&
          content == other.content &&
          status == other.status;
}

/// Optional material draft committed atomically with a flight completion.
class FlightCompletionMaterialDto {
  final String title;
  final String kind;
  final String? sourceUrl;
  final String? domain;
  final String? localAssetPath;
  final String tags;
  final PlatformInt64? rating;

  const FlightCompletionMaterialDto({
    required this.title,
    required this.kind,
    this.sourceUrl,
    this.domain,
    this.localAssetPath,
    required this.tags,
    this.rating,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      kind.hashCode ^
      sourceUrl.hashCode ^
      domain.hashCode ^
      localAssetPath.hashCode ^
      tags.hashCode ^
      rating.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlightCompletionMaterialDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          kind == other.kind &&
          sourceUrl == other.sourceUrl &&
          domain == other.domain &&
          localAssetPath == other.localAssetPath &&
          tags == other.tags &&
          rating == other.rating;
}

/// A material linked to a flight.
class FlightMaterialDto {
  final PlatformInt64 flightId;
  final PlatformInt64 sortOrder;
  final MaterialDto material;

  const FlightMaterialDto({
    required this.flightId,
    required this.sortOrder,
    required this.material,
  });

  @override
  int get hashCode =>
      flightId.hashCode ^ sortOrder.hashCode ^ material.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlightMaterialDto &&
          runtimeType == other.runtimeType &&
          flightId == other.flightId &&
          sortOrder == other.sortOrder &&
          material == other.material;
}

/// A flight session record.
class FlightSessionDto {
  final PlatformInt64 id;
  final String startedAt;
  final String? endedAt;
  final PlatformInt64? durationSecs;
  final String status;
  final PlatformInt64? satisfaction;
  final String note;
  final String date;

  const FlightSessionDto({
    required this.id,
    required this.startedAt,
    this.endedAt,
    this.durationSecs,
    required this.status,
    this.satisfaction,
    required this.note,
    required this.date,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      startedAt.hashCode ^
      endedAt.hashCode ^
      durationSecs.hashCode ^
      status.hashCode ^
      satisfaction.hashCode ^
      note.hashCode ^
      date.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlightSessionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          startedAt == other.startedAt &&
          endedAt == other.endedAt &&
          durationSecs == other.durationSecs &&
          status == other.status &&
          satisfaction == other.satisfaction &&
          note == other.note &&
          date == other.date;
}

/// Raw RGBA icon pixels for rendering in Flutter.
class IconDto {
  final PlatformInt64 width;
  final PlatformInt64 height;
  final Uint8List rgba;

  const IconDto({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IconDto &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}

/// A material record.
class MaterialDto {
  final PlatformInt64 id;
  final String title;
  final String kind;
  final String? sourceUrl;
  final String? domain;
  final String? localAssetPath;
  final String tags;
  final PlatformInt64? rating;

  const MaterialDto({
    required this.id,
    required this.title,
    required this.kind,
    this.sourceUrl,
    this.domain,
    this.localAssetPath,
    required this.tags,
    this.rating,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      kind.hashCode ^
      sourceUrl.hashCode ^
      domain.hashCode ^
      localAssetPath.hashCode ^
      tags.hashCode ^
      rating.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MaterialDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          kind == other.kind &&
          sourceUrl == other.sourceUrl &&
          domain == other.domain &&
          localAssetPath == other.localAssetPath &&
          tags == other.tags &&
          rating == other.rating;
}

class PageDto {
  final String title;
  final PlatformInt64 seconds;

  const PageDto({required this.title, required this.seconds});

  @override
  int get hashCode => title.hashCode ^ seconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          seconds == other.seconds;
}

class StartupDto {
  final PlatformInt64 id;
  final String name;
  final String exePath;
  final String source;
  final bool enabled;

  const StartupDto({
    required this.id,
    required this.name,
    required this.exePath,
    required this.source,
    required this.enabled,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      exePath.hashCode ^
      source.hashCode ^
      enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartupDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          exePath == other.exePath &&
          source == other.source &&
          enabled == other.enabled;
}

class StatsDto {
  final PlatformInt64 activeSeconds;
  final PlatformInt64 idleSeconds;
  final PlatformInt64 totalSeconds;
  final String? since;

  const StatsDto({
    required this.activeSeconds,
    required this.idleSeconds,
    required this.totalSeconds,
    this.since,
  });

  @override
  int get hashCode =>
      activeSeconds.hashCode ^
      idleSeconds.hashCode ^
      totalSeconds.hashCode ^
      since.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsDto &&
          runtimeType == other.runtimeType &&
          activeSeconds == other.activeSeconds &&
          idleSeconds == other.idleSeconds &&
          totalSeconds == other.totalSeconds &&
          since == other.since;
}
