// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clean_exe_path`, `parse_date`, `setup_logging`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TimeTraceApi>>
abstract class TimeTraceApi implements RustOpaqueInterface {
  /// Clear ALL tracked usage data (sessions + page visits).
  void clearData();

  /// Create the API, opening the DB and starting the background monitor.
  static TimeTraceApi create({required String dbPath}) =>
      RustLib.instance.api.crateApiTimeTraceApiCreate(dbPath: dbPath);

  /// Export usage data for a date range as CSV.
  /// Returns the CSV text (app, date, active_secs, idle_secs).
  String exportCsv({required String start, required String end});

  /// Extract an exe icon as raw RGBA pixels.
  IconDto? getAppIcon({required String exePath});

  /// Read the current user configuration.
  ConfigDto getConfig();

  /// One-call dashboard payload: usage split + overall stats.
  DashboardDataDto getDashboardData({
    required String start,
    required String end,
  });

  /// All startup entries.
  List<StartupDto> getStartupEntries();

  /// Overall recording statistics.
  StatsDto getStats({required String start, required String end});

  /// Per-app active/idle split for a date range (dates as "YYYY-MM-DD").
  List<AppUsageDto> getUsageSplit({required String start, required String end});

  /// Active seconds for this week (Mon→today) and last week (full).
  (PlatformInt64, PlatformInt64) getWeekTotals();

  /// Page-level breakdown for an app on a date.
  List<PageDto> getWindowTitles({
    required String appName,
    required String date,
  });

  /// Whether tracking is currently paused.
  bool isTrackingPaused();

  /// Resolve a startup command line to its clean exe path (env-expanded,
  /// quotes/args stripped). Returns None if no .exe is found.
  String? resolveExePath({required String command});

  /// Persist user configuration (applies on next monitor start).
  void setConfig({required ConfigDto config});

  /// Pause or resume the background tracking monitor.
  void setTrackingPaused({required bool paused});

  /// Enable/disable a startup entry.
  void toggleStartup({required PlatformInt64 id, required bool enable});
}

class AppUsageDto {
  final String appName;
  final PlatformInt64 activeSeconds;
  final PlatformInt64 idleSeconds;
  final String exePath;

  const AppUsageDto({
    required this.appName,
    required this.activeSeconds,
    required this.idleSeconds,
    required this.exePath,
  });

  @override
  int get hashCode =>
      appName.hashCode ^
      activeSeconds.hashCode ^
      idleSeconds.hashCode ^
      exePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppUsageDto &&
          runtimeType == other.runtimeType &&
          appName == other.appName &&
          activeSeconds == other.activeSeconds &&
          idleSeconds == other.idleSeconds &&
          exePath == other.exePath;
}

/// User configuration (persisted in AppConfig.json).
class ConfigDto {
  final BigInt pollIntervalMs;
  final BigInt idleThresholdMinutes;
  final List<String> excludedApps;
  final String dbPath;

  const ConfigDto({
    required this.pollIntervalMs,
    required this.idleThresholdMinutes,
    required this.excludedApps,
    required this.dbPath,
  });

  @override
  int get hashCode =>
      pollIntervalMs.hashCode ^
      idleThresholdMinutes.hashCode ^
      excludedApps.hashCode ^
      dbPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigDto &&
          runtimeType == other.runtimeType &&
          pollIntervalMs == other.pollIntervalMs &&
          idleThresholdMinutes == other.idleThresholdMinutes &&
          excludedApps == other.excludedApps &&
          dbPath == other.dbPath;
}

/// Combined dashboard payload (one FFI call instead of two).
class DashboardDataDto {
  final List<AppUsageDto> apps;
  final PlatformInt64 activeSeconds;
  final PlatformInt64 idleSeconds;
  final PlatformInt64 totalSeconds;
  final String? since;

  const DashboardDataDto({
    required this.apps,
    required this.activeSeconds,
    required this.idleSeconds,
    required this.totalSeconds,
    this.since,
  });

  @override
  int get hashCode =>
      apps.hashCode ^
      activeSeconds.hashCode ^
      idleSeconds.hashCode ^
      totalSeconds.hashCode ^
      since.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DashboardDataDto &&
          runtimeType == other.runtimeType &&
          apps == other.apps &&
          activeSeconds == other.activeSeconds &&
          idleSeconds == other.idleSeconds &&
          totalSeconds == other.totalSeconds &&
          since == other.since;
}

/// Raw RGBA icon pixels for rendering in Flutter.
class IconDto {
  final PlatformInt64 width;
  final PlatformInt64 height;
  final Uint8List rgba;

  const IconDto({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IconDto &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}

class PageDto {
  final String title;
  final PlatformInt64 seconds;

  const PageDto({required this.title, required this.seconds});

  @override
  int get hashCode => title.hashCode ^ seconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          seconds == other.seconds;
}

class StartupDto {
  final PlatformInt64 id;
  final String name;
  final String exePath;
  final String source;
  final bool enabled;

  const StartupDto({
    required this.id,
    required this.name,
    required this.exePath,
    required this.source,
    required this.enabled,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      exePath.hashCode ^
      source.hashCode ^
      enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartupDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          exePath == other.exePath &&
          source == other.source &&
          enabled == other.enabled;
}

class StatsDto {
  final PlatformInt64 activeSeconds;
  final PlatformInt64 idleSeconds;
  final PlatformInt64 totalSeconds;
  final String? since;

  const StatsDto({
    required this.activeSeconds,
    required this.idleSeconds,
    required this.totalSeconds,
    this.since,
  });

  @override
  int get hashCode =>
      activeSeconds.hashCode ^
      idleSeconds.hashCode ^
      totalSeconds.hashCode ^
      since.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsDto &&
          runtimeType == other.runtimeType &&
          activeSeconds == other.activeSeconds &&
          idleSeconds == other.idleSeconds &&
          totalSeconds == other.totalSeconds &&
          since == other.since;
}
