// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clean_exe_path`, `csv_field`, `parse_date`, `setup_logging`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TimeTraceApi>>
abstract class TimeTraceApi implements RustOpaqueInterface {
  /// Add a new diary entry for a date. Returns the new entry id.
  PlatformInt64 addDiaryEntry({required String date, required String content});

  /// Register a diary image for a date.
  String addDiaryImage({required String date, required String path});

  /// Clear ALL tracked usage data (sessions + page visits).
  void clearData();

  /// Create the API, opening the DB and starting the background monitor.
  static TimeTraceApi create({required String dbPath}) =>
      RustLib.instance.api.crateApiTimeTraceApiCreate(dbPath: dbPath);

  /// Delete a diary entry by id.
  void deleteDiaryEntry({required PlatformInt64 id});

  /// Export usage data for a date range as CSV.
  /// Returns the CSV text (app, date, active_secs, idle_secs).
  String exportCsv({required String start, required String end});

  /// Hourly active-seconds for one app on a date (24 buckets).
  Int64List getAppHourly({required String appName, required String date});

  /// Extract an exe icon as raw RGBA pixels.
  IconDto? getAppIcon({required String exePath});

  /// Read the current user configuration.
  ConfigDto getConfig();

  /// One-call dashboard payload: usage split + overall stats.
  DashboardDataDto getDashboardData({
    required String start,
    required String end,
  });

  /// Full day detail: active/idle totals, session timeline, diary.
  DayDetailDto getDayDetail({required String date});

  /// Hourly active-seconds for a day (24 buckets) — for the heatmap.
  Int64List getDayHourly({required String date});

  /// The day's draft content, if any.
  String? getDiaryDraft({required String date});

  /// Get all diary entries for a month range (for calendar markers).
  List<(String, String)> getDiaryEntries({
    required String start,
    required String end,
  });

  /// All diary entries in a range with ids + status, newest first.
  List<DiaryEntryDto> getDiaryEntriesDetailed({
    required String start,
    required String end,
  });

  /// Diary image paths in a date range (for calendar cell overlays).
  List<(String, String)> getDiaryImages({
    required String start,
    required String end,
  });

  /// All diary images with their entry link: (date, entry_id, path).
  List<(String, PlatformInt64?, String)> getDiaryImagesDetailed({
    required String start,
    required String end,
  });

  /// Image paths attached to a diary entry (朋友圈 album).
  List<String> getDiaryImagesForEntry({required PlatformInt64 entryId});

  /// Apps active within a specific hour of a date (seconds per app).
  List<AppUsageDto> getHourApps({required String date, required int hour});

  /// All startup entries.
  List<StartupDto> getStartupEntries();

  /// Overall recording statistics.
  StatsDto getStats({required String start, required String end});

  /// Per-app active/idle split for a date range (dates as "YYYY-MM-DD").
  List<AppUsageDto> getUsageSplit({required String start, required String end});

  /// Active seconds for this week (Mon→today) and last week (full).
  (PlatformInt64, PlatformInt64) getWeekTotals();

  /// Page-level breakdown for an app on a date.
  List<PageDto> getWindowTitles({
    required String appName,
    required String date,
  });

  /// Reports whether a database read has entered its non-panicking fallback.
  bool isDatabaseDegraded();

  /// Returns whether TimeTrace is configured to start for the current user.
  bool isSelfStartEnabled();

  /// Whether tracking is currently paused.
  bool isTrackingPaused();

  /// Publish: promote the day's draft or insert a new published entry.
  PlatformInt64 publishDiary({required String date, required String content});

  /// Atomically publish an AI-authored diary with model provenance.
  PlatformInt64 publishAiDiary({
    required String date,
    required String content,
    required String sourceModel,
  });

  /// Remove a diary image.
  void removeDiaryImage({required String path});

  /// Resolve a startup command line to its clean exe path (env-expanded,
  /// quotes/args stripped). Returns None if no .exe is found.
  String? resolveExePath({required String command});

  /// Autosave a draft for a date (one draft per day). Returns its id.
  PlatformInt64 saveDiaryDraft({required String date, required String content});

  /// Persist user configuration (applies on next monitor start).
  void setConfig({required ConfigDto config});

  /// Set the diary entry for a date.
  String setDiary({required String date, required String content});

  /// Link a staged diary image to a diary entry.
  void setDiaryImageEntry({
    required String path,
    required PlatformInt64 entryId,
  });

  /// Configures current-user startup without requiring administrator rights.
  void setSelfStartEnabled({required bool enabled, required bool minimized});

  /// Pause or resume the background tracking monitor.
  void setTrackingPaused({required bool paused});

  /// Enable/disable a startup entry.
  void toggleStartup({required PlatformInt64 id, required bool enable});

  /// Update a diary entry's content by id.
  void updateDiaryEntry({required PlatformInt64 id, required String content});
}

class AppUsageDto {
  final String appName;
  final PlatformInt64 activeSeconds;
  final PlatformInt64 idleSeconds;
  final String exePath;

  const AppUsageDto({
    required this.appName,
    required this.activeSeconds,
    required this.idleSeconds,
    required this.exePath,
  });

  @override
  int get hashCode =>
      appName.hashCode ^
      activeSeconds.hashCode ^
      idleSeconds.hashCode ^
      exePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppUsageDto &&
          runtimeType == other.runtimeType &&
          appName == other.appName &&
          activeSeconds == other.activeSeconds &&
          idleSeconds == other.idleSeconds &&
          exePath == other.exePath;
}

/// User configuration (persisted in AppConfig.json).
class ConfigDto {
  final BigInt pollIntervalMs;
  final BigInt idleThresholdMinutes;
  final bool minimizeToTray;
  final bool startMinimized;
  final bool autoStartTracking;
  final List<String> excludedApps;
  final String dbPath;

  const ConfigDto({
    required this.pollIntervalMs,
    required this.idleThresholdMinutes,
    required this.minimizeToTray,
    required this.startMinimized,
    required this.autoStartTracking,
    required this.excludedApps,
    required this.dbPath,
  });

  @override
  int get hashCode =>
      pollIntervalMs.hashCode ^
      idleThresholdMinutes.hashCode ^
      minimizeToTray.hashCode ^
      startMinimized.hashCode ^
      autoStartTracking.hashCode ^
      excludedApps.hashCode ^
      dbPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigDto &&
          runtimeType == other.runtimeType &&
          pollIntervalMs == other.pollIntervalMs &&
          idleThresholdMinutes == other.idleThresholdMinutes &&
          minimizeToTray == other.minimizeToTray &&
          startMinimized == other.startMinimized &&
          autoStartTracking == other.autoStartTracking &&
          excludedApps == other.excludedApps &&
          dbPath == other.dbPath;
}

/// Combined dashboard payload (one FFI call instead of two).
class DashboardDataDto {
  final List<AppUsageDto> apps;
  final PlatformInt64 activeSeconds;
  final PlatformInt64 idleSeconds;
  final PlatformInt64 totalSeconds;
  final String? since;

  const DashboardDataDto({
    required this.apps,
    required this.activeSeconds,
    required this.idleSeconds,
    required this.totalSeconds,
    this.since,
  });

  @override
  int get hashCode =>
      apps.hashCode ^
      activeSeconds.hashCode ^
      idleSeconds.hashCode ^
      totalSeconds.hashCode ^
      since.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DashboardDataDto &&
          runtimeType == other.runtimeType &&
          apps == other.apps &&
          activeSeconds == other.activeSeconds &&
          idleSeconds == other.idleSeconds &&
          totalSeconds == other.totalSeconds &&
          since == other.since;
}

/// A day's detail: summary + sessions + diary.
class DayDetailDto {
  final String date;
  final PlatformInt64 activeSeconds;
  final PlatformInt64 idleSeconds;
  final PlatformInt64 sessionCount;
  final String diary;
  final List<DaySessionDto> sessions;

  const DayDetailDto({
    required this.date,
    required this.activeSeconds,
    required this.idleSeconds,
    required this.sessionCount,
    required this.diary,
    required this.sessions,
  });

  @override
  int get hashCode =>
      date.hashCode ^
      activeSeconds.hashCode ^
      idleSeconds.hashCode ^
      sessionCount.hashCode ^
      diary.hashCode ^
      sessions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DayDetailDto &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          activeSeconds == other.activeSeconds &&
          idleSeconds == other.idleSeconds &&
          sessionCount == other.sessionCount &&
          diary == other.diary &&
          sessions == other.sessions;
}

/// A single day's session record (for the daily log).
class DaySessionDto {
  final String appName;
  final bool isIdle;
  final PlatformInt64 durationSecs;
  final String startedAt;

  const DaySessionDto({
    required this.appName,
    required this.isIdle,
    required this.durationSecs,
    required this.startedAt,
  });

  @override
  int get hashCode =>
      appName.hashCode ^
      isIdle.hashCode ^
      durationSecs.hashCode ^
      startedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DaySessionDto &&
          runtimeType == other.runtimeType &&
          appName == other.appName &&
          isIdle == other.isIdle &&
          durationSecs == other.durationSecs &&
          startedAt == other.startedAt;
}

/// A diary entry with its publish status and structured provenance.
class DiaryEntryDto {
  final PlatformInt64 id;
  final String date;
  final String content;
  final String status;
  final String source;
  final String? sourceModel;

  const DiaryEntryDto({
    required this.id,
    required this.date,
    required this.content,
    required this.status,
    required this.source,
    this.sourceModel,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      date.hashCode ^
      content.hashCode ^
      status.hashCode ^
      source.hashCode ^
      sourceModel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiaryEntryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          date == other.date &&
          content == other.content &&
          status == other.status &&
          source == other.source &&
          sourceModel == other.sourceModel;
}

/// Raw RGBA icon pixels for rendering in Flutter.
class IconDto {
  final PlatformInt64 width;
  final PlatformInt64 height;
  final Uint8List rgba;

  const IconDto({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IconDto &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}

class PageDto {
  final String title;
  final PlatformInt64 seconds;

  const PageDto({required this.title, required this.seconds});

  @override
  int get hashCode => title.hashCode ^ seconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          seconds == other.seconds;
}

class StartupDto {
  final PlatformInt64 id;
  final String name;
  final String exePath;
  final String source;
  final bool enabled;

  const StartupDto({
    required this.id,
    required this.name,
    required this.exePath,
    required this.source,
    required this.enabled,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      exePath.hashCode ^
      source.hashCode ^
      enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartupDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          exePath == other.exePath &&
          source == other.source &&
          enabled == other.enabled;
}

class StatsDto {
  final PlatformInt64 activeSeconds;
  final PlatformInt64 idleSeconds;
  final PlatformInt64 totalSeconds;
  final String? since;

  const StatsDto({
    required this.activeSeconds,
    required this.idleSeconds,
    required this.totalSeconds,
    this.since,
  });

  @override
  int get hashCode =>
      activeSeconds.hashCode ^
      idleSeconds.hashCode ^
      totalSeconds.hashCode ^
      since.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsDto &&
          runtimeType == other.runtimeType &&
          activeSeconds == other.activeSeconds &&
          idleSeconds == other.idleSeconds &&
          totalSeconds == other.totalSeconds &&
          since == other.since;
}
