// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1560329493;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'timetrace_bridge',
        ioDirectory: '../bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  PlatformInt64 crateApiTimeTraceApiAddDiaryEntry({
    required TimeTraceApi that,
    required String date,
    required String content,
  });

  String crateApiTimeTraceApiAddDiaryImage({
    required TimeTraceApi that,
    required String date,
    required String path,
  });

  void crateApiTimeTraceApiClearData({required TimeTraceApi that});

  TimeTraceApi crateApiTimeTraceApiCreate({required String dbPath});

  void crateApiTimeTraceApiDeleteDiaryEntry({
    required TimeTraceApi that,
    required PlatformInt64 id,
  });

  String crateApiTimeTraceApiExportCsv({
    required TimeTraceApi that,
    required String start,
    required String end,
  });

  Int64List crateApiTimeTraceApiGetAppHourly({
    required TimeTraceApi that,
    required String appName,
    required String date,
  });

  IconDto? crateApiTimeTraceApiGetAppIcon({
    required TimeTraceApi that,
    required String exePath,
  });

  ConfigDto crateApiTimeTraceApiGetConfig({required TimeTraceApi that});

  DashboardDataDto crateApiTimeTraceApiGetDashboardData({
    required TimeTraceApi that,
    required String start,
    required String end,
  });

  DayDetailDto crateApiTimeTraceApiGetDayDetail({
    required TimeTraceApi that,
    required String date,
  });

  Int64List crateApiTimeTraceApiGetDayHourly({
    required TimeTraceApi that,
    required String date,
  });

  String? crateApiTimeTraceApiGetDiaryDraft({
    required TimeTraceApi that,
    required String date,
  });

  List<(String, String)> crateApiTimeTraceApiGetDiaryEntries({
    required TimeTraceApi that,
    required String start,
    required String end,
  });

  List<DiaryEntryDto> crateApiTimeTraceApiGetDiaryEntriesDetailed({
    required TimeTraceApi that,
    required String start,
    required String end,
  });

  List<(String, String)> crateApiTimeTraceApiGetDiaryImages({
    required TimeTraceApi that,
    required String start,
    required String end,
  });

  List<(String, PlatformInt64?, String)>
  crateApiTimeTraceApiGetDiaryImagesDetailed({
    required TimeTraceApi that,
    required String start,
    required String end,
  });

  List<String> crateApiTimeTraceApiGetDiaryImagesForEntry({
    required TimeTraceApi that,
    required PlatformInt64 entryId,
  });

  List<AppUsageDto> crateApiTimeTraceApiGetHourApps({
    required TimeTraceApi that,
    required String date,
    required int hour,
  });

  List<StartupDto> crateApiTimeTraceApiGetStartupEntries({
    required TimeTraceApi that,
  });

  StatsDto crateApiTimeTraceApiGetStats({
    required TimeTraceApi that,
    required String start,
    required String end,
  });

  List<AppUsageDto> crateApiTimeTraceApiGetUsageSplit({
    required TimeTraceApi that,
    required String start,
    required String end,
  });

  (PlatformInt64, PlatformInt64) crateApiTimeTraceApiGetWeekTotals({
    required TimeTraceApi that,
  });

  List<PageDto> crateApiTimeTraceApiGetWindowTitles({
    required TimeTraceApi that,
    required String appName,
    required String date,
  });

  bool crateApiTimeTraceApiIsDatabaseDegraded({required TimeTraceApi that});

  bool crateApiTimeTraceApiIsSelfStartEnabled({required TimeTraceApi that});

  bool crateApiTimeTraceApiIsTrackingPaused({required TimeTraceApi that});

  PlatformInt64 crateApiTimeTraceApiPublishDiary({
    required TimeTraceApi that,
    required String date,
    required String content,
  });

  void crateApiTimeTraceApiRemoveDiaryImage({
    required TimeTraceApi that,
    required String path,
  });

  String? crateApiTimeTraceApiResolveExePath({
    required TimeTraceApi that,
    required String command,
  });

  PlatformInt64 crateApiTimeTraceApiSaveDiaryDraft({
    required TimeTraceApi that,
    required String date,
    required String content,
  });

  void crateApiTimeTraceApiSetConfig({
    required TimeTraceApi that,
    required ConfigDto config,
  });

  String crateApiTimeTraceApiSetDiary({
    required TimeTraceApi that,
    required String date,
    required String content,
  });

  void crateApiTimeTraceApiSetDiaryImageEntry({
    required TimeTraceApi that,
    required String path,
    required PlatformInt64 entryId,
  });

  void crateApiTimeTraceApiSetSelfStartEnabled({
    required TimeTraceApi that,
    required bool enabled,
    required bool minimized,
  });

  void crateApiTimeTraceApiSetTrackingPaused({
    required TimeTraceApi that,
    required bool paused,
  });

  void crateApiTimeTraceApiToggleStartup({
    required TimeTraceApi that,
    required PlatformInt64 id,
    required bool enable,
  });

  void crateApiTimeTraceApiUpdateDiaryEntry({
    required TimeTraceApi that,
    required PlatformInt64 id,
    required String content,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TimeTraceApi;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TimeTraceApi;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TimeTraceApiPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  PlatformInt64 crateApiTimeTraceApiAddDiaryEntry({
    required TimeTraceApi that,
    required String date,
    required String content,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(date, serializer);
          sse_encode_String(content, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiAddDiaryEntryConstMeta,
        argValues: [that, date, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiAddDiaryEntryConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_add_diary_entry",
        argNames: ["that", "date", "content"],
      );

  @override
  String crateApiTimeTraceApiAddDiaryImage({
    required TimeTraceApi that,
    required String date,
    required String path,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(date, serializer);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiAddDiaryImageConstMeta,
        argValues: [that, date, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiAddDiaryImageConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_add_diary_image",
        argNames: ["that", "date", "path"],
      );

  @override
  void crateApiTimeTraceApiClearData({required TimeTraceApi that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiClearDataConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiClearDataConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_clear_data",
        argNames: ["that"],
      );

  @override
  TimeTraceApi crateApiTimeTraceApiCreate({required String dbPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTimeTraceApiCreateConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiCreateConstMeta => const TaskConstMeta(
    debugName: "TimeTraceApi_create",
    argNames: ["dbPath"],
  );

  @override
  void crateApiTimeTraceApiDeleteDiaryEntry({
    required TimeTraceApi that,
    required PlatformInt64 id,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTimeTraceApiDeleteDiaryEntryConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiDeleteDiaryEntryConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_delete_diary_entry",
        argNames: ["that", "id"],
      );

  @override
  String crateApiTimeTraceApiExportCsv({
    required TimeTraceApi that,
    required String start,
    required String end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(start, serializer);
          sse_encode_String(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiExportCsvConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiExportCsvConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_export_csv",
        argNames: ["that", "start", "end"],
      );

  @override
  Int64List crateApiTimeTraceApiGetAppHourly({
    required TimeTraceApi that,
    required String appName,
    required String date,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(appName, serializer);
          sse_encode_String(date, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_i_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetAppHourlyConstMeta,
        argValues: [that, appName, date],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetAppHourlyConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_app_hourly",
        argNames: ["that", "appName", "date"],
      );

  @override
  IconDto? crateApiTimeTraceApiGetAppIcon({
    required TimeTraceApi that,
    required String exePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(exePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_icon_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetAppIconConstMeta,
        argValues: [that, exePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetAppIconConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_app_icon",
        argNames: ["that", "exePath"],
      );

  @override
  ConfigDto crateApiTimeTraceApiGetConfig({required TimeTraceApi that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_config_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetConfigConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetConfigConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_config",
        argNames: ["that"],
      );

  @override
  DashboardDataDto crateApiTimeTraceApiGetDashboardData({
    required TimeTraceApi that,
    required String start,
    required String end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(start, serializer);
          sse_encode_String(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dashboard_data_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetDashboardDataConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetDashboardDataConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_dashboard_data",
        argNames: ["that", "start", "end"],
      );

  @override
  DayDetailDto crateApiTimeTraceApiGetDayDetail({
    required TimeTraceApi that,
    required String date,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(date, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_day_detail_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetDayDetailConstMeta,
        argValues: [that, date],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetDayDetailConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_day_detail",
        argNames: ["that", "date"],
      );

  @override
  Int64List crateApiTimeTraceApiGetDayHourly({
    required TimeTraceApi that,
    required String date,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(date, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_i_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetDayHourlyConstMeta,
        argValues: [that, date],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetDayHourlyConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_day_hourly",
        argNames: ["that", "date"],
      );

  @override
  String? crateApiTimeTraceApiGetDiaryDraft({
    required TimeTraceApi that,
    required String date,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(date, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetDiaryDraftConstMeta,
        argValues: [that, date],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetDiaryDraftConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_diary_draft",
        argNames: ["that", "date"],
      );

  @override
  List<(String, String)> crateApiTimeTraceApiGetDiaryEntries({
    required TimeTraceApi that,
    required String start,
    required String end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(start, serializer);
          sse_encode_String(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_record_string_string,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetDiaryEntriesConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetDiaryEntriesConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_diary_entries",
        argNames: ["that", "start", "end"],
      );

  @override
  List<DiaryEntryDto> crateApiTimeTraceApiGetDiaryEntriesDetailed({
    required TimeTraceApi that,
    required String start,
    required String end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(start, serializer);
          sse_encode_String(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_diary_entry_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetDiaryEntriesDetailedConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetDiaryEntriesDetailedConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_diary_entries_detailed",
        argNames: ["that", "start", "end"],
      );

  @override
  List<(String, String)> crateApiTimeTraceApiGetDiaryImages({
    required TimeTraceApi that,
    required String start,
    required String end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(start, serializer);
          sse_encode_String(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_record_string_string,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetDiaryImagesConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetDiaryImagesConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_diary_images",
        argNames: ["that", "start", "end"],
      );

  @override
  List<(String, PlatformInt64?, String)>
  crateApiTimeTraceApiGetDiaryImagesDetailed({
    required TimeTraceApi that,
    required String start,
    required String end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(start, serializer);
          sse_encode_String(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_list_record_string_opt_box_autoadd_i_64_string,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetDiaryImagesDetailedConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetDiaryImagesDetailedConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_diary_images_detailed",
        argNames: ["that", "start", "end"],
      );

  @override
  List<String> crateApiTimeTraceApiGetDiaryImagesForEntry({
    required TimeTraceApi that,
    required PlatformInt64 entryId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_i_64(entryId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetDiaryImagesForEntryConstMeta,
        argValues: [that, entryId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetDiaryImagesForEntryConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_diary_images_for_entry",
        argNames: ["that", "entryId"],
      );

  @override
  List<AppUsageDto> crateApiTimeTraceApiGetHourApps({
    required TimeTraceApi that,
    required String date,
    required int hour,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(date, serializer);
          sse_encode_u_32(hour, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_app_usage_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetHourAppsConstMeta,
        argValues: [that, date, hour],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetHourAppsConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_hour_apps",
        argNames: ["that", "date", "hour"],
      );

  @override
  List<StartupDto> crateApiTimeTraceApiGetStartupEntries({
    required TimeTraceApi that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_startup_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetStartupEntriesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetStartupEntriesConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_startup_entries",
        argNames: ["that"],
      );

  @override
  StatsDto crateApiTimeTraceApiGetStats({
    required TimeTraceApi that,
    required String start,
    required String end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(start, serializer);
          sse_encode_String(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stats_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetStatsConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetStatsConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_stats",
        argNames: ["that", "start", "end"],
      );

  @override
  List<AppUsageDto> crateApiTimeTraceApiGetUsageSplit({
    required TimeTraceApi that,
    required String start,
    required String end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(start, serializer);
          sse_encode_String(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_app_usage_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetUsageSplitConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetUsageSplitConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_usage_split",
        argNames: ["that", "start", "end"],
      );

  @override
  (PlatformInt64, PlatformInt64) crateApiTimeTraceApiGetWeekTotals({
    required TimeTraceApi that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_i_64_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetWeekTotalsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetWeekTotalsConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_week_totals",
        argNames: ["that"],
      );

  @override
  List<PageDto> crateApiTimeTraceApiGetWindowTitles({
    required TimeTraceApi that,
    required String appName,
    required String date,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(appName, serializer);
          sse_encode_String(date, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_page_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetWindowTitlesConstMeta,
        argValues: [that, appName, date],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetWindowTitlesConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_window_titles",
        argNames: ["that", "appName", "date"],
      );

  @override
  bool crateApiTimeTraceApiIsDatabaseDegraded({required TimeTraceApi that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiIsDatabaseDegradedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiIsDatabaseDegradedConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_is_database_degraded",
        argNames: ["that"],
      );

  @override
  bool crateApiTimeTraceApiIsSelfStartEnabled({required TimeTraceApi that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTimeTraceApiIsSelfStartEnabledConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiIsSelfStartEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_is_self_start_enabled",
        argNames: ["that"],
      );

  @override
  bool crateApiTimeTraceApiIsTrackingPaused({required TimeTraceApi that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiIsTrackingPausedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiIsTrackingPausedConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_is_tracking_paused",
        argNames: ["that"],
      );

  @override
  PlatformInt64 crateApiTimeTraceApiPublishDiary({
    required TimeTraceApi that,
    required String date,
    required String content,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(date, serializer);
          sse_encode_String(content, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiPublishDiaryConstMeta,
        argValues: [that, date, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiPublishDiaryConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_publish_diary",
        argNames: ["that", "date", "content"],
      );

  @override
  void crateApiTimeTraceApiRemoveDiaryImage({
    required TimeTraceApi that,
    required String path,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiRemoveDiaryImageConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiRemoveDiaryImageConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_remove_diary_image",
        argNames: ["that", "path"],
      );

  @override
  String? crateApiTimeTraceApiResolveExePath({
    required TimeTraceApi that,
    required String command,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(command, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiResolveExePathConstMeta,
        argValues: [that, command],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiResolveExePathConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_resolve_exe_path",
        argNames: ["that", "command"],
      );

  @override
  PlatformInt64 crateApiTimeTraceApiSaveDiaryDraft({
    required TimeTraceApi that,
    required String date,
    required String content,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(date, serializer);
          sse_encode_String(content, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiSaveDiaryDraftConstMeta,
        argValues: [that, date, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiSaveDiaryDraftConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_save_diary_draft",
        argNames: ["that", "date", "content"],
      );

  @override
  void crateApiTimeTraceApiSetConfig({
    required TimeTraceApi that,
    required ConfigDto config,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_box_autoadd_config_dto(config, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTimeTraceApiSetConfigConstMeta,
        argValues: [that, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiSetConfigConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_set_config",
        argNames: ["that", "config"],
      );

  @override
  String crateApiTimeTraceApiSetDiary({
    required TimeTraceApi that,
    required String date,
    required String content,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(date, serializer);
          sse_encode_String(content, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiSetDiaryConstMeta,
        argValues: [that, date, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiSetDiaryConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_set_diary",
        argNames: ["that", "date", "content"],
      );

  @override
  void crateApiTimeTraceApiSetDiaryImageEntry({
    required TimeTraceApi that,
    required String path,
    required PlatformInt64 entryId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          sse_encode_i_64(entryId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTimeTraceApiSetDiaryImageEntryConstMeta,
        argValues: [that, path, entryId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiSetDiaryImageEntryConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_set_diary_image_entry",
        argNames: ["that", "path", "entryId"],
      );

  @override
  void crateApiTimeTraceApiSetSelfStartEnabled({
    required TimeTraceApi that,
    required bool enabled,
    required bool minimized,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_bool(enabled, serializer);
          sse_encode_bool(minimized, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTimeTraceApiSetSelfStartEnabledConstMeta,
        argValues: [that, enabled, minimized],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiSetSelfStartEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_set_self_start_enabled",
        argNames: ["that", "enabled", "minimized"],
      );

  @override
  void crateApiTimeTraceApiSetTrackingPaused({
    required TimeTraceApi that,
    required bool paused,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_bool(paused, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiSetTrackingPausedConstMeta,
        argValues: [that, paused],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiSetTrackingPausedConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_set_tracking_paused",
        argNames: ["that", "paused"],
      );

  @override
  void crateApiTimeTraceApiToggleStartup({
    required TimeTraceApi that,
    required PlatformInt64 id,
    required bool enable,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_i_64(id, serializer);
          sse_encode_bool(enable, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTimeTraceApiToggleStartupConstMeta,
        argValues: [that, id, enable],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiToggleStartupConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_toggle_startup",
        argNames: ["that", "id", "enable"],
      );

  @override
  void crateApiTimeTraceApiUpdateDiaryEntry({
    required TimeTraceApi that,
    required PlatformInt64 id,
    required String content,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_i_64(id, serializer);
          sse_encode_String(content, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTimeTraceApiUpdateDiaryEntryConstMeta,
        argValues: [that, id, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiUpdateDiaryEntryConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_update_diary_entry",
        argNames: ["that", "id", "content"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TimeTraceApi => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TimeTraceApi => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  TimeTraceApi
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TimeTraceApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TimeTraceApi
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TimeTraceApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TimeTraceApi
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TimeTraceApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppUsageDto dco_decode_app_usage_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AppUsageDto(
      appName: dco_decode_String(arr[0]),
      activeSeconds: dco_decode_i_64(arr[1]),
      idleSeconds: dco_decode_i_64(arr[2]),
      exePath: dco_decode_String(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ConfigDto dco_decode_box_autoadd_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_config_dto(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  IconDto dco_decode_box_autoadd_icon_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_icon_dto(raw);
  }

  @protected
  ConfigDto dco_decode_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ConfigDto(
      pollIntervalMs: dco_decode_u_64(arr[0]),
      idleThresholdMinutes: dco_decode_u_64(arr[1]),
      minimizeToTray: dco_decode_bool(arr[2]),
      startMinimized: dco_decode_bool(arr[3]),
      autoStartTracking: dco_decode_bool(arr[4]),
      excludedApps: dco_decode_list_String(arr[5]),
      dbPath: dco_decode_String(arr[6]),
    );
  }

  @protected
  DashboardDataDto dco_decode_dashboard_data_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DashboardDataDto(
      apps: dco_decode_list_app_usage_dto(arr[0]),
      activeSeconds: dco_decode_i_64(arr[1]),
      idleSeconds: dco_decode_i_64(arr[2]),
      totalSeconds: dco_decode_i_64(arr[3]),
      since: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  DayDetailDto dco_decode_day_detail_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return DayDetailDto(
      date: dco_decode_String(arr[0]),
      activeSeconds: dco_decode_i_64(arr[1]),
      idleSeconds: dco_decode_i_64(arr[2]),
      sessionCount: dco_decode_i_64(arr[3]),
      diary: dco_decode_String(arr[4]),
      sessions: dco_decode_list_day_session_dto(arr[5]),
    );
  }

  @protected
  DaySessionDto dco_decode_day_session_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DaySessionDto(
      appName: dco_decode_String(arr[0]),
      isIdle: dco_decode_bool(arr[1]),
      durationSecs: dco_decode_i_64(arr[2]),
      startedAt: dco_decode_String(arr[3]),
    );
  }

  @protected
  DiaryEntryDto dco_decode_diary_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DiaryEntryDto(
      id: dco_decode_i_64(arr[0]),
      date: dco_decode_String(arr[1]),
      content: dco_decode_String(arr[2]),
      status: dco_decode_String(arr[3]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IconDto dco_decode_icon_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return IconDto(
      width: dco_decode_i_64(arr[0]),
      height: dco_decode_i_64(arr[1]),
      rgba: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AppUsageDto> dco_decode_list_app_usage_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_app_usage_dto).toList();
  }

  @protected
  List<DaySessionDto> dco_decode_list_day_session_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_day_session_dto).toList();
  }

  @protected
  List<DiaryEntryDto> dco_decode_list_diary_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_diary_entry_dto).toList();
  }

  @protected
  List<PageDto> dco_decode_list_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_page_dto).toList();
  }

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeInt64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, PlatformInt64?, String)>
  dco_decode_list_record_string_opt_box_autoadd_i_64_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_opt_box_autoadd_i_64_string)
        .toList();
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<StartupDto> dco_decode_list_startup_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_startup_dto).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  IconDto? dco_decode_opt_box_autoadd_icon_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_icon_dto(raw);
  }

  @protected
  PageDto dco_decode_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PageDto(
      title: dco_decode_String(arr[0]),
      seconds: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  (PlatformInt64, PlatformInt64) dco_decode_record_i_64_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_i_64(arr[0]), dco_decode_i_64(arr[1]));
  }

  @protected
  (String, PlatformInt64?, String)
  dco_decode_record_string_opt_box_autoadd_i_64_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) {
      throw Exception('Expected 3 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_opt_box_autoadd_i_64(arr[1]),
      dco_decode_String(arr[2]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  StartupDto dco_decode_startup_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return StartupDto(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      exePath: dco_decode_String(arr[2]),
      source: dco_decode_String(arr[3]),
      enabled: dco_decode_bool(arr[4]),
    );
  }

  @protected
  StatsDto dco_decode_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return StatsDto(
      activeSeconds: dco_decode_i_64(arr[0]),
      idleSeconds: dco_decode_i_64(arr[1]),
      totalSeconds: dco_decode_i_64(arr[2]),
      since: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  TimeTraceApi
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TimeTraceApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TimeTraceApi
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TimeTraceApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TimeTraceApi
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TimeTraceApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppUsageDto sse_decode_app_usage_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_appName = sse_decode_String(deserializer);
    var var_activeSeconds = sse_decode_i_64(deserializer);
    var var_idleSeconds = sse_decode_i_64(deserializer);
    var var_exePath = sse_decode_String(deserializer);
    return AppUsageDto(
      appName: var_appName,
      activeSeconds: var_activeSeconds,
      idleSeconds: var_idleSeconds,
      exePath: var_exePath,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ConfigDto sse_decode_box_autoadd_config_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_config_dto(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  IconDto sse_decode_box_autoadd_icon_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_icon_dto(deserializer));
  }

  @protected
  ConfigDto sse_decode_config_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pollIntervalMs = sse_decode_u_64(deserializer);
    var var_idleThresholdMinutes = sse_decode_u_64(deserializer);
    var var_minimizeToTray = sse_decode_bool(deserializer);
    var var_startMinimized = sse_decode_bool(deserializer);
    var var_autoStartTracking = sse_decode_bool(deserializer);
    var var_excludedApps = sse_decode_list_String(deserializer);
    var var_dbPath = sse_decode_String(deserializer);
    return ConfigDto(
      pollIntervalMs: var_pollIntervalMs,
      idleThresholdMinutes: var_idleThresholdMinutes,
      minimizeToTray: var_minimizeToTray,
      startMinimized: var_startMinimized,
      autoStartTracking: var_autoStartTracking,
      excludedApps: var_excludedApps,
      dbPath: var_dbPath,
    );
  }

  @protected
  DashboardDataDto sse_decode_dashboard_data_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_apps = sse_decode_list_app_usage_dto(deserializer);
    var var_activeSeconds = sse_decode_i_64(deserializer);
    var var_idleSeconds = sse_decode_i_64(deserializer);
    var var_totalSeconds = sse_decode_i_64(deserializer);
    var var_since = sse_decode_opt_String(deserializer);
    return DashboardDataDto(
      apps: var_apps,
      activeSeconds: var_activeSeconds,
      idleSeconds: var_idleSeconds,
      totalSeconds: var_totalSeconds,
      since: var_since,
    );
  }

  @protected
  DayDetailDto sse_decode_day_detail_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_date = sse_decode_String(deserializer);
    var var_activeSeconds = sse_decode_i_64(deserializer);
    var var_idleSeconds = sse_decode_i_64(deserializer);
    var var_sessionCount = sse_decode_i_64(deserializer);
    var var_diary = sse_decode_String(deserializer);
    var var_sessions = sse_decode_list_day_session_dto(deserializer);
    return DayDetailDto(
      date: var_date,
      activeSeconds: var_activeSeconds,
      idleSeconds: var_idleSeconds,
      sessionCount: var_sessionCount,
      diary: var_diary,
      sessions: var_sessions,
    );
  }

  @protected
  DaySessionDto sse_decode_day_session_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_appName = sse_decode_String(deserializer);
    var var_isIdle = sse_decode_bool(deserializer);
    var var_durationSecs = sse_decode_i_64(deserializer);
    var var_startedAt = sse_decode_String(deserializer);
    return DaySessionDto(
      appName: var_appName,
      isIdle: var_isIdle,
      durationSecs: var_durationSecs,
      startedAt: var_startedAt,
    );
  }

  @protected
  DiaryEntryDto sse_decode_diary_entry_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_date = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    return DiaryEntryDto(
      id: var_id,
      date: var_date,
      content: var_content,
      status: var_status,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IconDto sse_decode_icon_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_i_64(deserializer);
    var var_height = sse_decode_i_64(deserializer);
    var var_rgba = sse_decode_list_prim_u_8_strict(deserializer);
    return IconDto(width: var_width, height: var_height, rgba: var_rgba);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AppUsageDto> sse_decode_list_app_usage_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AppUsageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_app_usage_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<DaySessionDto> sse_decode_list_day_session_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DaySessionDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_day_session_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<DiaryEntryDto> sse_decode_list_diary_entry_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DiaryEntryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_diary_entry_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<PageDto> sse_decode_list_page_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_page_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, PlatformInt64?, String)>
  sse_decode_list_record_string_opt_box_autoadd_i_64_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, PlatformInt64?, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
        sse_decode_record_string_opt_box_autoadd_i_64_string(deserializer),
      );
    }
    return ans_;
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<StartupDto> sse_decode_list_startup_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StartupDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_startup_dto(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  IconDto? sse_decode_opt_box_autoadd_icon_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_icon_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PageDto sse_decode_page_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_seconds = sse_decode_i_64(deserializer);
    return PageDto(title: var_title, seconds: var_seconds);
  }

  @protected
  (PlatformInt64, PlatformInt64) sse_decode_record_i_64_i_64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_i_64(deserializer);
    var var_field1 = sse_decode_i_64(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (String, PlatformInt64?, String)
  sse_decode_record_string_opt_box_autoadd_i_64_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_field2 = sse_decode_String(deserializer);
    return (var_field0, var_field1, var_field2);
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  StartupDto sse_decode_startup_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_exePath = sse_decode_String(deserializer);
    var var_source = sse_decode_String(deserializer);
    var var_enabled = sse_decode_bool(deserializer);
    return StartupDto(
      id: var_id,
      name: var_name,
      exePath: var_exePath,
      source: var_source,
      enabled: var_enabled,
    );
  }

  @protected
  StatsDto sse_decode_stats_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_activeSeconds = sse_decode_i_64(deserializer);
    var var_idleSeconds = sse_decode_i_64(deserializer);
    var var_totalSeconds = sse_decode_i_64(deserializer);
    var var_since = sse_decode_opt_String(deserializer);
    return StatsDto(
      activeSeconds: var_activeSeconds,
      idleSeconds: var_idleSeconds,
      totalSeconds: var_totalSeconds,
      since: var_since,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    TimeTraceApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TimeTraceApiImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    TimeTraceApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TimeTraceApiImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    TimeTraceApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TimeTraceApiImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_usage_dto(AppUsageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.appName, serializer);
    sse_encode_i_64(self.activeSeconds, serializer);
    sse_encode_i_64(self.idleSeconds, serializer);
    sse_encode_String(self.exePath, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_config_dto(
    ConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_config_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_icon_dto(IconDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_icon_dto(self, serializer);
  }

  @protected
  void sse_encode_config_dto(ConfigDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.pollIntervalMs, serializer);
    sse_encode_u_64(self.idleThresholdMinutes, serializer);
    sse_encode_bool(self.minimizeToTray, serializer);
    sse_encode_bool(self.startMinimized, serializer);
    sse_encode_bool(self.autoStartTracking, serializer);
    sse_encode_list_String(self.excludedApps, serializer);
    sse_encode_String(self.dbPath, serializer);
  }

  @protected
  void sse_encode_dashboard_data_dto(
    DashboardDataDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_app_usage_dto(self.apps, serializer);
    sse_encode_i_64(self.activeSeconds, serializer);
    sse_encode_i_64(self.idleSeconds, serializer);
    sse_encode_i_64(self.totalSeconds, serializer);
    sse_encode_opt_String(self.since, serializer);
  }

  @protected
  void sse_encode_day_detail_dto(DayDetailDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.date, serializer);
    sse_encode_i_64(self.activeSeconds, serializer);
    sse_encode_i_64(self.idleSeconds, serializer);
    sse_encode_i_64(self.sessionCount, serializer);
    sse_encode_String(self.diary, serializer);
    sse_encode_list_day_session_dto(self.sessions, serializer);
  }

  @protected
  void sse_encode_day_session_dto(
    DaySessionDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.appName, serializer);
    sse_encode_bool(self.isIdle, serializer);
    sse_encode_i_64(self.durationSecs, serializer);
    sse_encode_String(self.startedAt, serializer);
  }

  @protected
  void sse_encode_diary_entry_dto(
    DiaryEntryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.date, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_icon_dto(IconDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.width, serializer);
    sse_encode_i_64(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.rgba, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_app_usage_dto(
    List<AppUsageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_app_usage_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_day_session_dto(
    List<DaySessionDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_day_session_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_diary_entry_dto(
    List<DiaryEntryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_diary_entry_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_page_dto(List<PageDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_page_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_opt_box_autoadd_i_64_string(
    List<(String, PlatformInt64?, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_opt_box_autoadd_i_64_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_startup_dto(
    List<StartupDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_startup_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_icon_dto(
    IconDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_icon_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_page_dto(PageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.seconds, serializer);
  }

  @protected
  void sse_encode_record_i_64_i_64(
    (PlatformInt64, PlatformInt64) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.$1, serializer);
    sse_encode_i_64(self.$2, serializer);
  }

  @protected
  void sse_encode_record_string_opt_box_autoadd_i_64_string(
    (String, PlatformInt64?, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_opt_box_autoadd_i_64(self.$2, serializer);
    sse_encode_String(self.$3, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_startup_dto(StartupDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.exePath, serializer);
    sse_encode_String(self.source, serializer);
    sse_encode_bool(self.enabled, serializer);
  }

  @protected
  void sse_encode_stats_dto(StatsDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.activeSeconds, serializer);
    sse_encode_i_64(self.idleSeconds, serializer);
    sse_encode_i_64(self.totalSeconds, serializer);
    sse_encode_opt_String(self.since, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class TimeTraceApiImpl extends RustOpaque implements TimeTraceApi {
  // Not to be used by end users
  TimeTraceApiImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TimeTraceApiImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_TimeTraceApi,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_TimeTraceApi,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_TimeTraceApiPtr,
  );

  /// Add a new diary entry for a date. Returns the new entry id.
  PlatformInt64 addDiaryEntry({
    required String date,
    required String content,
  }) => RustLib.instance.api.crateApiTimeTraceApiAddDiaryEntry(
    that: this,
    date: date,
    content: content,
  );

  /// Register a diary image for a date.
  String addDiaryImage({required String date, required String path}) => RustLib
      .instance
      .api
      .crateApiTimeTraceApiAddDiaryImage(that: this, date: date, path: path);

  /// Clear ALL tracked usage data (sessions + page visits).
  void clearData() =>
      RustLib.instance.api.crateApiTimeTraceApiClearData(that: this);

  /// Delete a diary entry by id.
  void deleteDiaryEntry({required PlatformInt64 id}) => RustLib.instance.api
      .crateApiTimeTraceApiDeleteDiaryEntry(that: this, id: id);

  /// Export usage data for a date range as CSV.
  /// Returns the CSV text (app, date, active_secs, idle_secs).
  String exportCsv({required String start, required String end}) => RustLib
      .instance
      .api
      .crateApiTimeTraceApiExportCsv(that: this, start: start, end: end);

  /// Hourly active-seconds for one app on a date (24 buckets).
  Int64List getAppHourly({required String appName, required String date}) =>
      RustLib.instance.api.crateApiTimeTraceApiGetAppHourly(
        that: this,
        appName: appName,
        date: date,
      );

  /// Extract an exe icon as raw RGBA pixels.
  IconDto? getAppIcon({required String exePath}) => RustLib.instance.api
      .crateApiTimeTraceApiGetAppIcon(that: this, exePath: exePath);

  /// Read the current user configuration.
  ConfigDto getConfig() =>
      RustLib.instance.api.crateApiTimeTraceApiGetConfig(that: this);

  /// One-call dashboard payload: usage split + overall stats.
  DashboardDataDto getDashboardData({
    required String start,
    required String end,
  }) => RustLib.instance.api.crateApiTimeTraceApiGetDashboardData(
    that: this,
    start: start,
    end: end,
  );

  /// Full day detail: active/idle totals, session timeline, diary.
  DayDetailDto getDayDetail({required String date}) => RustLib.instance.api
      .crateApiTimeTraceApiGetDayDetail(that: this, date: date);

  /// Hourly active-seconds for a day (24 buckets) — for the heatmap.
  Int64List getDayHourly({required String date}) => RustLib.instance.api
      .crateApiTimeTraceApiGetDayHourly(that: this, date: date);

  /// The day's draft content, if any.
  String? getDiaryDraft({required String date}) => RustLib.instance.api
      .crateApiTimeTraceApiGetDiaryDraft(that: this, date: date);

  /// Get all diary entries for a month range (for calendar markers).
  List<(String, String)> getDiaryEntries({
    required String start,
    required String end,
  }) => RustLib.instance.api.crateApiTimeTraceApiGetDiaryEntries(
    that: this,
    start: start,
    end: end,
  );

  /// All diary entries in a range with ids + status, newest first.
  List<DiaryEntryDto> getDiaryEntriesDetailed({
    required String start,
    required String end,
  }) => RustLib.instance.api.crateApiTimeTraceApiGetDiaryEntriesDetailed(
    that: this,
    start: start,
    end: end,
  );

  /// Diary image paths in a date range (for calendar cell overlays).
  List<(String, String)> getDiaryImages({
    required String start,
    required String end,
  }) => RustLib.instance.api.crateApiTimeTraceApiGetDiaryImages(
    that: this,
    start: start,
    end: end,
  );

  /// All diary images with their entry link: (date, entry_id, path).
  List<(String, PlatformInt64?, String)> getDiaryImagesDetailed({
    required String start,
    required String end,
  }) => RustLib.instance.api.crateApiTimeTraceApiGetDiaryImagesDetailed(
    that: this,
    start: start,
    end: end,
  );

  /// Image paths attached to a diary entry (朋友圈 album).
  List<String> getDiaryImagesForEntry({required PlatformInt64 entryId}) =>
      RustLib.instance.api.crateApiTimeTraceApiGetDiaryImagesForEntry(
        that: this,
        entryId: entryId,
      );

  /// Apps active within a specific hour of a date (seconds per app).
  List<AppUsageDto> getHourApps({required String date, required int hour}) =>
      RustLib.instance.api.crateApiTimeTraceApiGetHourApps(
        that: this,
        date: date,
        hour: hour,
      );

  /// All startup entries.
  List<StartupDto> getStartupEntries() =>
      RustLib.instance.api.crateApiTimeTraceApiGetStartupEntries(that: this);

  /// Overall recording statistics.
  StatsDto getStats({required String start, required String end}) => RustLib
      .instance
      .api
      .crateApiTimeTraceApiGetStats(that: this, start: start, end: end);

  /// Per-app active/idle split for a date range (dates as "YYYY-MM-DD").
  List<AppUsageDto> getUsageSplit({
    required String start,
    required String end,
  }) => RustLib.instance.api.crateApiTimeTraceApiGetUsageSplit(
    that: this,
    start: start,
    end: end,
  );

  /// Active seconds for this week (Mon→today) and last week (full).
  (PlatformInt64, PlatformInt64) getWeekTotals() =>
      RustLib.instance.api.crateApiTimeTraceApiGetWeekTotals(that: this);

  /// Page-level breakdown for an app on a date.
  List<PageDto> getWindowTitles({
    required String appName,
    required String date,
  }) => RustLib.instance.api.crateApiTimeTraceApiGetWindowTitles(
    that: this,
    appName: appName,
    date: date,
  );

  /// Reports whether a database read has entered its non-panicking fallback.
  bool isDatabaseDegraded() =>
      RustLib.instance.api.crateApiTimeTraceApiIsDatabaseDegraded(that: this);

  /// Returns whether TimeTrace is configured to start for the current user.
  bool isSelfStartEnabled() =>
      RustLib.instance.api.crateApiTimeTraceApiIsSelfStartEnabled(that: this);

  /// Whether tracking is currently paused.
  bool isTrackingPaused() =>
      RustLib.instance.api.crateApiTimeTraceApiIsTrackingPaused(that: this);

  /// Publish: promote the day's draft or insert a new published entry.
  PlatformInt64 publishDiary({required String date, required String content}) =>
      RustLib.instance.api.crateApiTimeTraceApiPublishDiary(
        that: this,
        date: date,
        content: content,
      );

  /// Remove a diary image.
  void removeDiaryImage({required String path}) => RustLib.instance.api
      .crateApiTimeTraceApiRemoveDiaryImage(that: this, path: path);

  /// Resolve a startup command line to its clean exe path (env-expanded,
  /// quotes/args stripped). Returns None if no .exe is found.
  String? resolveExePath({required String command}) => RustLib.instance.api
      .crateApiTimeTraceApiResolveExePath(that: this, command: command);

  /// Autosave a draft for a date (one draft per day). Returns its id.
  PlatformInt64 saveDiaryDraft({
    required String date,
    required String content,
  }) => RustLib.instance.api.crateApiTimeTraceApiSaveDiaryDraft(
    that: this,
    date: date,
    content: content,
  );

  /// Persist user configuration (applies on next monitor start).
  void setConfig({required ConfigDto config}) => RustLib.instance.api
      .crateApiTimeTraceApiSetConfig(that: this, config: config);

  /// Set the diary entry for a date.
  String setDiary({required String date, required String content}) => RustLib
      .instance
      .api
      .crateApiTimeTraceApiSetDiary(that: this, date: date, content: content);

  /// Link a staged diary image to a diary entry.
  void setDiaryImageEntry({
    required String path,
    required PlatformInt64 entryId,
  }) => RustLib.instance.api.crateApiTimeTraceApiSetDiaryImageEntry(
    that: this,
    path: path,
    entryId: entryId,
  );

  /// Configures current-user startup without requiring administrator rights.
  void setSelfStartEnabled({required bool enabled, required bool minimized}) =>
      RustLib.instance.api.crateApiTimeTraceApiSetSelfStartEnabled(
        that: this,
        enabled: enabled,
        minimized: minimized,
      );

  /// Pause or resume the background tracking monitor.
  void setTrackingPaused({required bool paused}) => RustLib.instance.api
      .crateApiTimeTraceApiSetTrackingPaused(that: this, paused: paused);

  /// Enable/disable a startup entry.
  void toggleStartup({required PlatformInt64 id, required bool enable}) =>
      RustLib.instance.api.crateApiTimeTraceApiToggleStartup(
        that: this,
        id: id,
        enable: enable,
      );

  /// Update a diary entry's content by id.
  void updateDiaryEntry({required PlatformInt64 id, required String content}) =>
      RustLib.instance.api.crateApiTimeTraceApiUpdateDiaryEntry(
        that: this,
        id: id,
        content: content,
      );
}
