// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'ai_recap.dart';
import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_TimeTraceApiPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  TimeTraceApi
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    dynamic raw,
  );

  @protected
  TimeTraceApi
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    dynamic raw,
  );

  @protected
  TimeTraceApi
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AiModelOptionDto dco_decode_ai_model_option_dto(dynamic raw);

  @protected
  AiProviderOptionDto dco_decode_ai_provider_option_dto(dynamic raw);

  @protected
  AiRecapConnectionReplyDto dco_decode_ai_recap_connection_reply_dto(
    dynamic raw,
  );

  @protected
  AiRecapDto dco_decode_ai_recap_dto(dynamic raw);

  @protected
  AiRecapErrorDto dco_decode_ai_recap_error_dto(dynamic raw);

  @protected
  AiRecapEvidenceDto dco_decode_ai_recap_evidence_dto(dynamic raw);

  @protected
  AiRecapGenerateReplyDto dco_decode_ai_recap_generate_reply_dto(dynamic raw);

  @protected
  AiRecapSettingsReplyDto dco_decode_ai_recap_settings_reply_dto(dynamic raw);

  @protected
  AiRecapStatementDto dco_decode_ai_recap_statement_dto(dynamic raw);

  @protected
  AiRecapStatusDto dco_decode_ai_recap_status_dto(dynamic raw);

  @protected
  AppUsageDto dco_decode_app_usage_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AiRecapDto dco_decode_box_autoadd_ai_recap_dto(dynamic raw);

  @protected
  AiRecapErrorDto dco_decode_box_autoadd_ai_recap_error_dto(dynamic raw);

  @protected
  ConfigDto dco_decode_box_autoadd_config_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  IconDto dco_decode_box_autoadd_icon_dto(dynamic raw);

  @protected
  ConfigDto dco_decode_config_dto(dynamic raw);

  @protected
  DashboardDataDto dco_decode_dashboard_data_dto(dynamic raw);

  @protected
  DayDetailDto dco_decode_day_detail_dto(dynamic raw);

  @protected
  DaySessionDto dco_decode_day_session_dto(dynamic raw);

  @protected
  DiaryEntryDto dco_decode_diary_entry_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IconDto dco_decode_icon_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AiModelOptionDto> dco_decode_list_ai_model_option_dto(dynamic raw);

  @protected
  List<AiProviderOptionDto> dco_decode_list_ai_provider_option_dto(dynamic raw);

  @protected
  List<AiRecapDto> dco_decode_list_ai_recap_dto(dynamic raw);

  @protected
  List<AiRecapEvidenceDto> dco_decode_list_ai_recap_evidence_dto(dynamic raw);

  @protected
  List<AiRecapStatementDto> dco_decode_list_ai_recap_statement_dto(dynamic raw);

  @protected
  List<AppUsageDto> dco_decode_list_app_usage_dto(dynamic raw);

  @protected
  List<DaySessionDto> dco_decode_list_day_session_dto(dynamic raw);

  @protected
  List<DiaryEntryDto> dco_decode_list_diary_entry_dto(dynamic raw);

  @protected
  List<PageDto> dco_decode_list_page_dto(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, PlatformInt64?, String)>
  dco_decode_list_record_string_opt_box_autoadd_i_64_string(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<StartupDto> dco_decode_list_startup_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AiRecapDto? dco_decode_opt_box_autoadd_ai_recap_dto(dynamic raw);

  @protected
  AiRecapErrorDto? dco_decode_opt_box_autoadd_ai_recap_error_dto(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  IconDto? dco_decode_opt_box_autoadd_icon_dto(dynamic raw);

  @protected
  PageDto dco_decode_page_dto(dynamic raw);

  @protected
  (PlatformInt64, PlatformInt64) dco_decode_record_i_64_i_64(dynamic raw);

  @protected
  (String, PlatformInt64?, String)
  dco_decode_record_string_opt_box_autoadd_i_64_string(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  StartupDto dco_decode_startup_dto(dynamic raw);

  @protected
  StatsDto dco_decode_stats_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  TimeTraceApi
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    SseDeserializer deserializer,
  );

  @protected
  TimeTraceApi
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    SseDeserializer deserializer,
  );

  @protected
  TimeTraceApi
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AiModelOptionDto sse_decode_ai_model_option_dto(SseDeserializer deserializer);

  @protected
  AiProviderOptionDto sse_decode_ai_provider_option_dto(
    SseDeserializer deserializer,
  );

  @protected
  AiRecapConnectionReplyDto sse_decode_ai_recap_connection_reply_dto(
    SseDeserializer deserializer,
  );

  @protected
  AiRecapDto sse_decode_ai_recap_dto(SseDeserializer deserializer);

  @protected
  AiRecapErrorDto sse_decode_ai_recap_error_dto(SseDeserializer deserializer);

  @protected
  AiRecapEvidenceDto sse_decode_ai_recap_evidence_dto(
    SseDeserializer deserializer,
  );

  @protected
  AiRecapGenerateReplyDto sse_decode_ai_recap_generate_reply_dto(
    SseDeserializer deserializer,
  );

  @protected
  AiRecapSettingsReplyDto sse_decode_ai_recap_settings_reply_dto(
    SseDeserializer deserializer,
  );

  @protected
  AiRecapStatementDto sse_decode_ai_recap_statement_dto(
    SseDeserializer deserializer,
  );

  @protected
  AiRecapStatusDto sse_decode_ai_recap_status_dto(SseDeserializer deserializer);

  @protected
  AppUsageDto sse_decode_app_usage_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AiRecapDto sse_decode_box_autoadd_ai_recap_dto(SseDeserializer deserializer);

  @protected
  AiRecapErrorDto sse_decode_box_autoadd_ai_recap_error_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConfigDto sse_decode_box_autoadd_config_dto(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  IconDto sse_decode_box_autoadd_icon_dto(SseDeserializer deserializer);

  @protected
  ConfigDto sse_decode_config_dto(SseDeserializer deserializer);

  @protected
  DashboardDataDto sse_decode_dashboard_data_dto(SseDeserializer deserializer);

  @protected
  DayDetailDto sse_decode_day_detail_dto(SseDeserializer deserializer);

  @protected
  DaySessionDto sse_decode_day_session_dto(SseDeserializer deserializer);

  @protected
  DiaryEntryDto sse_decode_diary_entry_dto(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IconDto sse_decode_icon_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AiModelOptionDto> sse_decode_list_ai_model_option_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AiProviderOptionDto> sse_decode_list_ai_provider_option_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AiRecapDto> sse_decode_list_ai_recap_dto(SseDeserializer deserializer);

  @protected
  List<AiRecapEvidenceDto> sse_decode_list_ai_recap_evidence_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AiRecapStatementDto> sse_decode_list_ai_recap_statement_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AppUsageDto> sse_decode_list_app_usage_dto(SseDeserializer deserializer);

  @protected
  List<DaySessionDto> sse_decode_list_day_session_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DiaryEntryDto> sse_decode_list_diary_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PageDto> sse_decode_list_page_dto(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, PlatformInt64?, String)>
  sse_decode_list_record_string_opt_box_autoadd_i_64_string(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<StartupDto> sse_decode_list_startup_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AiRecapDto? sse_decode_opt_box_autoadd_ai_recap_dto(
    SseDeserializer deserializer,
  );

  @protected
  AiRecapErrorDto? sse_decode_opt_box_autoadd_ai_recap_error_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  IconDto? sse_decode_opt_box_autoadd_icon_dto(SseDeserializer deserializer);

  @protected
  PageDto sse_decode_page_dto(SseDeserializer deserializer);

  @protected
  (PlatformInt64, PlatformInt64) sse_decode_record_i_64_i_64(
    SseDeserializer deserializer,
  );

  @protected
  (String, PlatformInt64?, String)
  sse_decode_record_string_opt_box_autoadd_i_64_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  StartupDto sse_decode_startup_dto(SseDeserializer deserializer);

  @protected
  StatsDto sse_decode_stats_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    TimeTraceApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    TimeTraceApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    TimeTraceApi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ai_model_option_dto(
    AiModelOptionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_provider_option_dto(
    AiProviderOptionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_recap_connection_reply_dto(
    AiRecapConnectionReplyDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_recap_dto(AiRecapDto self, SseSerializer serializer);

  @protected
  void sse_encode_ai_recap_error_dto(
    AiRecapErrorDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_recap_evidence_dto(
    AiRecapEvidenceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_recap_generate_reply_dto(
    AiRecapGenerateReplyDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_recap_settings_reply_dto(
    AiRecapSettingsReplyDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_recap_statement_dto(
    AiRecapStatementDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_recap_status_dto(
    AiRecapStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_app_usage_dto(AppUsageDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_recap_dto(
    AiRecapDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ai_recap_error_dto(
    AiRecapErrorDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_config_dto(
    ConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_icon_dto(IconDto self, SseSerializer serializer);

  @protected
  void sse_encode_config_dto(ConfigDto self, SseSerializer serializer);

  @protected
  void sse_encode_dashboard_data_dto(
    DashboardDataDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_day_detail_dto(DayDetailDto self, SseSerializer serializer);

  @protected
  void sse_encode_day_session_dto(DaySessionDto self, SseSerializer serializer);

  @protected
  void sse_encode_diary_entry_dto(DiaryEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_icon_dto(IconDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ai_model_option_dto(
    List<AiModelOptionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ai_provider_option_dto(
    List<AiProviderOptionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ai_recap_dto(
    List<AiRecapDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ai_recap_evidence_dto(
    List<AiRecapEvidenceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ai_recap_statement_dto(
    List<AiRecapStatementDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_app_usage_dto(
    List<AppUsageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_day_session_dto(
    List<DaySessionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_diary_entry_dto(
    List<DiaryEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_page_dto(List<PageDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_opt_box_autoadd_i_64_string(
    List<(String, PlatformInt64?, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_startup_dto(
    List<StartupDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ai_recap_dto(
    AiRecapDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ai_recap_error_dto(
    AiRecapErrorDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_icon_dto(
    IconDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_page_dto(PageDto self, SseSerializer serializer);

  @protected
  void sse_encode_record_i_64_i_64(
    (PlatformInt64, PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_opt_box_autoadd_i_64_string(
    (String, PlatformInt64?, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_startup_dto(StartupDto self, SseSerializer serializer);

  @protected
  void sse_encode_stats_dto(StatsDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    int ptr,
  );
}
