// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1643533028;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'timetrace_bridge',
        ioDirectory: '../bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  TimeTraceApi crateApiTimeTraceApiCreate({required String dbPath});

  IconDto? crateApiTimeTraceApiGetAppIcon({
    required TimeTraceApi that,
    required String exePath,
  });

  ConfigDto crateApiTimeTraceApiGetConfig({required TimeTraceApi that});

  List<StartupDto> crateApiTimeTraceApiGetStartupEntries({
    required TimeTraceApi that,
  });

  StatsDto crateApiTimeTraceApiGetStats({
    required TimeTraceApi that,
    required String start,
    required String end,
  });

  List<AppUsageDto> crateApiTimeTraceApiGetUsageSplit({
    required TimeTraceApi that,
    required String start,
    required String end,
  });

  List<PageDto> crateApiTimeTraceApiGetWindowTitles({
    required TimeTraceApi that,
    required String appName,
    required String date,
  });

  void crateApiTimeTraceApiSetConfig({
    required TimeTraceApi that,
    required ConfigDto config,
  });

  void crateApiTimeTraceApiToggleStartup({
    required TimeTraceApi that,
    required PlatformInt64 id,
    required bool enable,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TimeTraceApi;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TimeTraceApi;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TimeTraceApiPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  TimeTraceApi crateApiTimeTraceApiCreate({required String dbPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTimeTraceApiCreateConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiCreateConstMeta => const TaskConstMeta(
    debugName: "TimeTraceApi_create",
    argNames: ["dbPath"],
  );

  @override
  IconDto? crateApiTimeTraceApiGetAppIcon({
    required TimeTraceApi that,
    required String exePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(exePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_icon_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetAppIconConstMeta,
        argValues: [that, exePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetAppIconConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_app_icon",
        argNames: ["that", "exePath"],
      );

  @override
  ConfigDto crateApiTimeTraceApiGetConfig({required TimeTraceApi that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_config_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetConfigConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetConfigConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_config",
        argNames: ["that"],
      );

  @override
  List<StartupDto> crateApiTimeTraceApiGetStartupEntries({
    required TimeTraceApi that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_startup_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetStartupEntriesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetStartupEntriesConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_startup_entries",
        argNames: ["that"],
      );

  @override
  StatsDto crateApiTimeTraceApiGetStats({
    required TimeTraceApi that,
    required String start,
    required String end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(start, serializer);
          sse_encode_String(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stats_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetStatsConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetStatsConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_stats",
        argNames: ["that", "start", "end"],
      );

  @override
  List<AppUsageDto> crateApiTimeTraceApiGetUsageSplit({
    required TimeTraceApi that,
    required String start,
    required String end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(start, serializer);
          sse_encode_String(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_app_usage_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetUsageSplitConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetUsageSplitConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_usage_split",
        argNames: ["that", "start", "end"],
      );

  @override
  List<PageDto> crateApiTimeTraceApiGetWindowTitles({
    required TimeTraceApi that,
    required String appName,
    required String date,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_String(appName, serializer);
          sse_encode_String(date, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_page_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTimeTraceApiGetWindowTitlesConstMeta,
        argValues: [that, appName, date],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiGetWindowTitlesConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_get_window_titles",
        argNames: ["that", "appName", "date"],
      );

  @override
  void crateApiTimeTraceApiSetConfig({
    required TimeTraceApi that,
    required ConfigDto config,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_box_autoadd_config_dto(config, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTimeTraceApiSetConfigConstMeta,
        argValues: [that, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiSetConfigConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_set_config",
        argNames: ["that", "config"],
      );

  @override
  void crateApiTimeTraceApiToggleStartup({
    required TimeTraceApi that,
    required PlatformInt64 id,
    required bool enable,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
            that,
            serializer,
          );
          sse_encode_i_64(id, serializer);
          sse_encode_bool(enable, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTimeTraceApiToggleStartupConstMeta,
        argValues: [that, id, enable],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTimeTraceApiToggleStartupConstMeta =>
      const TaskConstMeta(
        debugName: "TimeTraceApi_toggle_startup",
        argNames: ["that", "id", "enable"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TimeTraceApi => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TimeTraceApi => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  TimeTraceApi
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TimeTraceApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TimeTraceApi
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TimeTraceApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TimeTraceApi
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TimeTraceApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppUsageDto dco_decode_app_usage_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AppUsageDto(
      appName: dco_decode_String(arr[0]),
      activeSeconds: dco_decode_i_64(arr[1]),
      idleSeconds: dco_decode_i_64(arr[2]),
      exePath: dco_decode_String(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ConfigDto dco_decode_box_autoadd_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_config_dto(raw);
  }

  @protected
  IconDto dco_decode_box_autoadd_icon_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_icon_dto(raw);
  }

  @protected
  ConfigDto dco_decode_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ConfigDto(
      pollIntervalMs: dco_decode_u_64(arr[0]),
      idleThresholdMinutes: dco_decode_u_64(arr[1]),
      excludedApps: dco_decode_list_String(arr[2]),
      dbPath: dco_decode_String(arr[3]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IconDto dco_decode_icon_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return IconDto(
      width: dco_decode_i_64(arr[0]),
      height: dco_decode_i_64(arr[1]),
      rgba: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AppUsageDto> dco_decode_list_app_usage_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_app_usage_dto).toList();
  }

  @protected
  List<PageDto> dco_decode_list_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_page_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<StartupDto> dco_decode_list_startup_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_startup_dto).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  IconDto? dco_decode_opt_box_autoadd_icon_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_icon_dto(raw);
  }

  @protected
  PageDto dco_decode_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PageDto(
      title: dco_decode_String(arr[0]),
      seconds: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  StartupDto dco_decode_startup_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return StartupDto(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      exePath: dco_decode_String(arr[2]),
      source: dco_decode_String(arr[3]),
      enabled: dco_decode_bool(arr[4]),
    );
  }

  @protected
  StatsDto dco_decode_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return StatsDto(
      activeSeconds: dco_decode_i_64(arr[0]),
      idleSeconds: dco_decode_i_64(arr[1]),
      totalSeconds: dco_decode_i_64(arr[2]),
      since: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  TimeTraceApi
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TimeTraceApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TimeTraceApi
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TimeTraceApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TimeTraceApi
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TimeTraceApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppUsageDto sse_decode_app_usage_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_appName = sse_decode_String(deserializer);
    var var_activeSeconds = sse_decode_i_64(deserializer);
    var var_idleSeconds = sse_decode_i_64(deserializer);
    var var_exePath = sse_decode_String(deserializer);
    return AppUsageDto(
      appName: var_appName,
      activeSeconds: var_activeSeconds,
      idleSeconds: var_idleSeconds,
      exePath: var_exePath,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ConfigDto sse_decode_box_autoadd_config_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_config_dto(deserializer));
  }

  @protected
  IconDto sse_decode_box_autoadd_icon_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_icon_dto(deserializer));
  }

  @protected
  ConfigDto sse_decode_config_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pollIntervalMs = sse_decode_u_64(deserializer);
    var var_idleThresholdMinutes = sse_decode_u_64(deserializer);
    var var_excludedApps = sse_decode_list_String(deserializer);
    var var_dbPath = sse_decode_String(deserializer);
    return ConfigDto(
      pollIntervalMs: var_pollIntervalMs,
      idleThresholdMinutes: var_idleThresholdMinutes,
      excludedApps: var_excludedApps,
      dbPath: var_dbPath,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IconDto sse_decode_icon_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_i_64(deserializer);
    var var_height = sse_decode_i_64(deserializer);
    var var_rgba = sse_decode_list_prim_u_8_strict(deserializer);
    return IconDto(width: var_width, height: var_height, rgba: var_rgba);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AppUsageDto> sse_decode_list_app_usage_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AppUsageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_app_usage_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<PageDto> sse_decode_list_page_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_page_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<StartupDto> sse_decode_list_startup_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StartupDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_startup_dto(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  IconDto? sse_decode_opt_box_autoadd_icon_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_icon_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PageDto sse_decode_page_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_seconds = sse_decode_i_64(deserializer);
    return PageDto(title: var_title, seconds: var_seconds);
  }

  @protected
  StartupDto sse_decode_startup_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_exePath = sse_decode_String(deserializer);
    var var_source = sse_decode_String(deserializer);
    var var_enabled = sse_decode_bool(deserializer);
    return StartupDto(
      id: var_id,
      name: var_name,
      exePath: var_exePath,
      source: var_source,
      enabled: var_enabled,
    );
  }

  @protected
  StatsDto sse_decode_stats_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_activeSeconds = sse_decode_i_64(deserializer);
    var var_idleSeconds = sse_decode_i_64(deserializer);
    var var_totalSeconds = sse_decode_i_64(deserializer);
    var var_since = sse_decode_opt_String(deserializer);
    return StatsDto(
      activeSeconds: var_activeSeconds,
      idleSeconds: var_idleSeconds,
      totalSeconds: var_totalSeconds,
      since: var_since,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    TimeTraceApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TimeTraceApiImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    TimeTraceApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TimeTraceApiImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimeTraceApi(
    TimeTraceApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TimeTraceApiImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_usage_dto(AppUsageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.appName, serializer);
    sse_encode_i_64(self.activeSeconds, serializer);
    sse_encode_i_64(self.idleSeconds, serializer);
    sse_encode_String(self.exePath, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_config_dto(
    ConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_config_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_icon_dto(IconDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_icon_dto(self, serializer);
  }

  @protected
  void sse_encode_config_dto(ConfigDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.pollIntervalMs, serializer);
    sse_encode_u_64(self.idleThresholdMinutes, serializer);
    sse_encode_list_String(self.excludedApps, serializer);
    sse_encode_String(self.dbPath, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_icon_dto(IconDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.width, serializer);
    sse_encode_i_64(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.rgba, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_app_usage_dto(
    List<AppUsageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_app_usage_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_page_dto(List<PageDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_page_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_startup_dto(
    List<StartupDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_startup_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_icon_dto(
    IconDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_icon_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_page_dto(PageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.seconds, serializer);
  }

  @protected
  void sse_encode_startup_dto(StartupDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.exePath, serializer);
    sse_encode_String(self.source, serializer);
    sse_encode_bool(self.enabled, serializer);
  }

  @protected
  void sse_encode_stats_dto(StatsDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.activeSeconds, serializer);
    sse_encode_i_64(self.idleSeconds, serializer);
    sse_encode_i_64(self.totalSeconds, serializer);
    sse_encode_opt_String(self.since, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class TimeTraceApiImpl extends RustOpaque implements TimeTraceApi {
  // Not to be used by end users
  TimeTraceApiImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TimeTraceApiImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_TimeTraceApi,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_TimeTraceApi,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_TimeTraceApiPtr,
  );

  /// Extract an exe icon as raw RGBA pixels.
  IconDto? getAppIcon({required String exePath}) => RustLib.instance.api
      .crateApiTimeTraceApiGetAppIcon(that: this, exePath: exePath);

  /// Read the current user configuration.
  ConfigDto getConfig() =>
      RustLib.instance.api.crateApiTimeTraceApiGetConfig(that: this);

  /// All startup entries.
  List<StartupDto> getStartupEntries() =>
      RustLib.instance.api.crateApiTimeTraceApiGetStartupEntries(that: this);

  /// Overall recording statistics.
  StatsDto getStats({required String start, required String end}) => RustLib
      .instance
      .api
      .crateApiTimeTraceApiGetStats(that: this, start: start, end: end);

  /// Per-app active/idle split for a date range (dates as "YYYY-MM-DD").
  List<AppUsageDto> getUsageSplit({
    required String start,
    required String end,
  }) => RustLib.instance.api.crateApiTimeTraceApiGetUsageSplit(
    that: this,
    start: start,
    end: end,
  );

  /// Page-level breakdown for an app on a date.
  List<PageDto> getWindowTitles({
    required String appName,
    required String date,
  }) => RustLib.instance.api.crateApiTimeTraceApiGetWindowTitles(
    that: this,
    appName: appName,
    date: date,
  );

  /// Persist user configuration (applies on next monitor start).
  void setConfig({required ConfigDto config}) => RustLib.instance.api
      .crateApiTimeTraceApiSetConfig(that: this, config: config);

  /// Enable/disable a startup entry.
  void toggleStartup({required PlatformInt64 id, required bool enable}) =>
      RustLib.instance.api.crateApiTimeTraceApiToggleStartup(
        that: this,
        id: id,
        enable: enable,
      );
}
