// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Closed native badge.
enum MarketplaceBadgeDto {
  official,
  verifiedPublisher,
  beta,
  suspended,
  revoked,
}

/// A closed consent capability accepted for the exact release only.
enum MarketplaceCapabilityDto { usageAggregateRead, aiCloud, aiLocal }

/// A verified, display-safe catalog release projection.
class MarketplaceCatalogItemDto {
  /// Exact release identity.
  final MarketplaceReleaseRefDto release;

  /// Plain text display label.
  final String displayName;

  /// Plain text description.
  final String? description;

  /// Closed channel.
  final MarketplaceChannelDto channel;

  /// Closed release state.
  final MarketplaceReleaseStateDto state;

  /// Closed badges.
  final List<MarketplaceBadgeDto> badges;

  /// Locally recomputed compatibility.
  final MarketplaceDispositionDto compatibility;

  /// Host-rendered permission review.
  final List<MarketplacePermissionReviewDto> permissions;

  /// Exact bounded package size.
  final BigInt packageBytes;

  /// Exact verified UTC millisecond spelling.
  final String publishedAt;

  const MarketplaceCatalogItemDto({
    required this.release,
    required this.displayName,
    this.description,
    required this.channel,
    required this.state,
    required this.badges,
    required this.compatibility,
    required this.permissions,
    required this.packageBytes,
    required this.publishedAt,
  });

  @override
  int get hashCode =>
      release.hashCode ^
      displayName.hashCode ^
      description.hashCode ^
      channel.hashCode ^
      state.hashCode ^
      badges.hashCode ^
      compatibility.hashCode ^
      permissions.hashCode ^
      packageBytes.hashCode ^
      publishedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarketplaceCatalogItemDto &&
          runtimeType == other.runtimeType &&
          release == other.release &&
          displayName == other.displayName &&
          description == other.description &&
          channel == other.channel &&
          state == other.state &&
          badges == other.badges &&
          compatibility == other.compatibility &&
          permissions == other.permissions &&
          packageBytes == other.packageBytes &&
          publishedAt == other.publishedAt;
}

/// A verified catalog page projection.
class MarketplaceCatalogPageDto {
  /// Marketplace schema version.
  final int schemaVersion;

  /// Opaque catalog revision.
  final String catalogRevision;

  /// Exact verified UTC millisecond spelling.
  final String generatedAt;

  /// At most fifty verified catalog items.
  final List<MarketplaceCatalogItemDto> items;

  /// Opaque next cursor.
  final String? nextCursor;

  const MarketplaceCatalogPageDto({
    required this.schemaVersion,
    required this.catalogRevision,
    required this.generatedAt,
    required this.items,
    this.nextCursor,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      catalogRevision.hashCode ^
      generatedAt.hashCode ^
      items.hashCode ^
      nextCursor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarketplaceCatalogPageDto &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          catalogRevision == other.catalogRevision &&
          generatedAt == other.generatedAt &&
          items == other.items &&
          nextCursor == other.nextCursor;
}

/// A bounded catalog request.  No URL, filters, or offsets cross FFI.
class MarketplaceCatalogQueryDto {
  /// `stable` or `beta`; empty selects the host default (`stable`).
  final String channel;

  /// Opaque cursor from an earlier verified page.
  final String? cursor;

  /// Requested page size, 1 through 50.
  final int limit;

  const MarketplaceCatalogQueryDto({
    required this.channel,
    this.cursor,
    required this.limit,
  });

  @override
  int get hashCode => channel.hashCode ^ cursor.hashCode ^ limit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarketplaceCatalogQueryDto &&
          runtimeType == other.runtimeType &&
          channel == other.channel &&
          cursor == other.cursor &&
          limit == other.limit;
}

/// Closed catalog channel.
enum MarketplaceChannelDto { stable, beta }

/// Closed install disposition.
enum MarketplaceDispositionDto {
  installable,
  updateAvailable,
  alreadyInstalled,
  downgradeBlocked,
  incompatibleHostApi,
  incompatiblePlatform,
  packageTooLarge,
  permissionRequired,
  blockedLocalPolicy,
  blockedSuspended,
  revoked,
}

/// Closed marketplace error code safe to display after local translation.
enum MarketplaceErrorCodeDto {
  catalogUnavailable,
  catalogInvalid,
  notFound,
  invalidRequest,
  packageUnavailable,
  packageTooLarge,
  digestMismatch,
  archiveInvalid,
  releaseIdentityMismatch,
  consentMismatch,
  storageUnavailable,
  cancelled,
  internal,
}

/// A host-issued, privacy-safe Marketplace error.
class MarketplaceErrorDto {
  /// Stable closed error code.
  final MarketplaceErrorCodeDto code;

  /// Whether the same request may be retried later.
  final bool retryable;

  /// Optional host correlation token; never a transport payload.
  final String? correlationId;

  const MarketplaceErrorDto({
    required this.code,
    required this.retryable,
    this.correlationId,
  });

  @override
  int get hashCode =>
      code.hashCode ^ retryable.hashCode ^ correlationId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarketplaceErrorDto &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          retryable == other.retryable &&
          correlationId == other.correlationId;
}

/// The exact plan to which consent is bound.
class MarketplaceInstallPlanDto {
  /// Exact selected release.
  final MarketplaceReleaseRefDto release;

  /// Closed local disposition.
  final MarketplaceDispositionDto disposition;

  /// Only permissions requiring fresh user consent.
  final List<MarketplacePermissionReviewDto> requiredConsent;

  /// Bounded local disk estimate.
  final BigInt diskBytes;

  const MarketplaceInstallPlanDto({
    required this.release,
    required this.disposition,
    required this.requiredConsent,
    required this.diskBytes,
  });

  @override
  int get hashCode =>
      release.hashCode ^
      disposition.hashCode ^
      requiredConsent.hashCode ^
      diskBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarketplaceInstallPlanDto &&
          runtimeType == other.runtimeType &&
          release == other.release &&
          disposition == other.disposition &&
          requiredConsent == other.requiredConsent &&
          diskBytes == other.diskBytes;
}

/// An exact immutable install request.
class MarketplaceInstallRequestDto {
  /// Reviewed immutable release identity.
  final MarketplaceReleaseRefDto release;

  /// Unique closed capability ids selected by the user. The host canonicalizes order.
  final List<MarketplaceCapabilityDto> consentCapabilityIds;

  const MarketplaceInstallRequestDto({
    required this.release,
    required this.consentCapabilityIds,
  });

  @override
  int get hashCode => release.hashCode ^ consentCapabilityIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarketplaceInstallRequestDto &&
          runtimeType == other.runtimeType &&
          release == other.release &&
          consentCapabilityIds == other.consentCapabilityIds;
}

/// Host-produced operation phase.
enum MarketplaceOperationPhaseDto {
  idle,
  checking,
  downloading,
  verifying,
  installing,
  enabled,
  blocked,
  failed,
}

/// Final safe operation snapshot.
class MarketplaceOperationStateDto {
  /// Closed operation phase.
  final MarketplaceOperationPhaseDto phase;

  /// Closed stable error when the phase is failed.
  final MarketplaceErrorDto? error;

  const MarketplaceOperationStateDto({required this.phase, this.error});

  @override
  int get hashCode => phase.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarketplaceOperationStateDto &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          error == other.error;
}

/// Presentation-safe reviewed permission data.
class MarketplacePermissionReviewDto {
  /// Closed capability identifier.
  final MarketplaceCapabilityDto capability;

  /// Host-generated constrained summary.
  final String summary;

  /// Host-generated optional rationale.
  final String? rationale;

  const MarketplacePermissionReviewDto({
    required this.capability,
    required this.summary,
    this.rationale,
  });

  @override
  int get hashCode =>
      capability.hashCode ^ summary.hashCode ^ rationale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarketplacePermissionReviewDto &&
          runtimeType == other.runtimeType &&
          capability == other.capability &&
          summary == other.summary &&
          rationale == other.rationale;
}

/// A verified plugin detail projection.
class MarketplacePluginDetailDto {
  /// Lookup identity.
  final String publisherId;

  /// Lookup identity.
  final String pluginId;

  /// Selected exact release.
  final MarketplaceCatalogItemDto selectedRelease;

  /// Other verified releases for the same identity.
  final List<MarketplaceCatalogItemDto> versions;

  /// Locally recomputed install plan.
  final MarketplaceInstallPlanDto installPlan;

  const MarketplacePluginDetailDto({
    required this.publisherId,
    required this.pluginId,
    required this.selectedRelease,
    required this.versions,
    required this.installPlan,
  });

  @override
  int get hashCode =>
      publisherId.hashCode ^
      pluginId.hashCode ^
      selectedRelease.hashCode ^
      versions.hashCode ^
      installPlan.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarketplacePluginDetailDto &&
          runtimeType == other.runtimeType &&
          publisherId == other.publisherId &&
          pluginId == other.pluginId &&
          selectedRelease == other.selectedRelease &&
          versions == other.versions &&
          installPlan == other.installPlan;
}

/// A publisher/plugin identity for a detail lookup.
class MarketplacePluginRefDto {
  /// Canonical publisher identifier.
  final String publisherId;

  /// Canonical plugin identifier.
  final String pluginId;

  const MarketplacePluginRefDto({
    required this.publisherId,
    required this.pluginId,
  });

  @override
  int get hashCode => publisherId.hashCode ^ pluginId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarketplacePluginRefDto &&
          runtimeType == other.runtimeType &&
          publisherId == other.publisherId &&
          pluginId == other.pluginId;
}

/// The immutable release the user reviewed.
class MarketplaceReleaseRefDto {
  /// Marketplace UUID release identifier.
  final String releaseId;

  /// Canonical publisher identifier.
  final String publisherId;

  /// Canonical plugin identifier.
  final String pluginId;

  /// Exact reviewed semantic version.
  final String version;

  /// Exact lowercase SHA-256 package digest.
  final String packageDigest;

  const MarketplaceReleaseRefDto({
    required this.releaseId,
    required this.publisherId,
    required this.pluginId,
    required this.version,
    required this.packageDigest,
  });

  @override
  int get hashCode =>
      releaseId.hashCode ^
      publisherId.hashCode ^
      pluginId.hashCode ^
      version.hashCode ^
      packageDigest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarketplaceReleaseRefDto &&
          runtimeType == other.runtimeType &&
          releaseId == other.releaseId &&
          publisherId == other.publisherId &&
          pluginId == other.pluginId &&
          version == other.version &&
          packageDigest == other.packageDigest;
}

/// Closed release availability state.
enum MarketplaceReleaseStateDto { published, suspended, revoked }
