// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'service.freezed.dart';

/// Flutter-facing immutable host contribution snapshot.
class HostContributionSnapshotDto {
  /// Host-owned monotonic complete-publication revision.
  final BigInt revision;

  /// Canonical plugin management states in plugin identifier order.
  final List<HostPluginUiStateDto> plugins;

  /// Currently projectable canonical contributions.
  final List<HostProjectedContributionDto> active;

  const HostContributionSnapshotDto({
    required this.revision,
    required this.plugins,
    required this.active,
  });

  @override
  int get hashCode => revision.hashCode ^ plugins.hashCode ^ active.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostContributionSnapshotDto &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          plugins == other.plugins &&
          active == other.active;
}

/// A typed, non-executable projection of one signed P1 document.
class HostDeclarativeV1DocumentDto {
  /// Canonical contribution identity bound to the fixed archive resource path.
  final String contributionId;

  /// Closed host-rendered root node.
  final HostDeclarativeV1NodeDto root;

  const HostDeclarativeV1DocumentDto({
    required this.contributionId,
    required this.root,
  });

  @override
  int get hashCode => contributionId.hashCode ^ root.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostDeclarativeV1DocumentDto &&
          runtimeType == other.runtimeType &&
          contributionId == other.contributionId &&
          root == other.root;
}

@freezed
sealed class HostDeclarativeV1NodeDto with _$HostDeclarativeV1NodeDto {
  const HostDeclarativeV1NodeDto._();

  /// Plain inert text.
  const factory HostDeclarativeV1NodeDto.text({required String text}) =
      HostDeclarativeV1NodeDto_Text;

  /// A host-rendered label/value pair.
  const factory HostDeclarativeV1NodeDto.metric({
    required String label,
    required String value,
  }) = HostDeclarativeV1NodeDto_Metric;

  /// Vertical host layout.
  const factory HostDeclarativeV1NodeDto.stack({
    required List<HostDeclarativeV1NodeDto> children,
  }) = HostDeclarativeV1NodeDto_Stack;

  /// Plain inert list items.
  const factory HostDeclarativeV1NodeDto.list({required List<String> items}) =
      HostDeclarativeV1NodeDto_List;
}

/// Flutter-facing lifecycle and canonical manifest state for one plugin.
class HostPluginUiStateDto {
  /// Canonical plugin identifier.
  final String pluginId;

  /// JSON serialized only from the canonical Rust manifest DTO.
  final String manifestJson;

  /// Canonical desired-state wire token.
  final String desiredState;

  /// Canonical runtime-state wire token.
  final String runtimeState;

  /// Whether host API and platform compatibility passed.
  final bool compatible;

  /// Whether activation grants are currently satisfied.
  final bool grantsSatisfied;

  /// Host lifecycle generation.
  final BigInt generation;

  /// Stable lifecycle failure token, when present.
  final String? failureCode;

  /// Whether the current failure may be retried.
  final bool failureRetryable;

  const HostPluginUiStateDto({
    required this.pluginId,
    required this.manifestJson,
    required this.desiredState,
    required this.runtimeState,
    required this.compatible,
    required this.grantsSatisfied,
    required this.generation,
    this.failureCode,
    required this.failureRetryable,
  });

  @override
  int get hashCode =>
      pluginId.hashCode ^
      manifestJson.hashCode ^
      desiredState.hashCode ^
      runtimeState.hashCode ^
      compatible.hashCode ^
      grantsSatisfied.hashCode ^
      generation.hashCode ^
      failureCode.hashCode ^
      failureRetryable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostPluginUiStateDto &&
          runtimeType == other.runtimeType &&
          pluginId == other.pluginId &&
          manifestJson == other.manifestJson &&
          desiredState == other.desiredState &&
          runtimeState == other.runtimeState &&
          compatible == other.compatible &&
          grantsSatisfied == other.grantsSatisfied &&
          generation == other.generation &&
          failureCode == other.failureCode &&
          failureRetryable == other.failureRetryable;
}

/// Flutter-facing active contribution serialized from canonical Rust DTOs.
class HostProjectedContributionDto {
  /// Canonical owning plugin identifier.
  final String pluginId;

  /// JSON serialized only from the canonical Rust contribution DTO.
  final String contributionJson;

  /// Host-generated extension route for pages and navigation destinations.
  final String? route;

  /// Fixed-path, host-parsed P1 document for declarative page/card content.
  final HostDeclarativeV1DocumentDto? declarativeDocument;

  const HostProjectedContributionDto({
    required this.pluginId,
    required this.contributionJson,
    this.route,
    this.declarativeDocument,
  });

  @override
  int get hashCode =>
      pluginId.hashCode ^
      contributionJson.hashCode ^
      route.hashCode ^
      declarativeDocument.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostProjectedContributionDto &&
          runtimeType == other.runtimeType &&
          pluginId == other.pluginId &&
          contributionJson == other.contributionJson &&
          route == other.route &&
          declarativeDocument == other.declarativeDocument;
}
